"""phase5 dd24 mfa policies credentials and challenges

DD-24 方案 A：策略（mfa_policies）/ 凭据（user_mfa）/ 挑战（mfa_challenges）三张表。
DD-23 方案 A：登录在二次验证通过**之后**才创建 Session，中间态由 mfa_challenges 承载。
DD-22 方案 A：user_mfa.encrypted_secret 存 AES-256-GCM 密文，故列类型为 Text（长度可变）。

为什么三张表而不是 `07 §7` 建议的一张
------------------------------------
`07 §7` 列出的 `user_mfa` 字段（provider / status / encrypted_secret / setup_at /
enabled_at / verified_at）**全部是凭据字段**，没有任何一处能表达 `04 §7` 要求的
"是否要求 MFA"；而角色级策略不属于任何用户，在 `user_mfa` 里无处安放。
强行合并只能放弃角色级策略（违反 `04 §7`），故策略与凭据分表。

为什么 `required` 可空
--------------------
`NULL` = 该层**未表态**（继续向下询问）；`False` = **明确不要求**（终止解析）。
二者合并会让"用户级实现一上线就永久屏蔽角色级策略"，且运行时看不出来 ——
该语义在 Phase 4 已由 `UnsetUserMfaPolicySource` 返回 `None` 固化，本表必须一致。

Revision ID: phase5_dd24
Revises: phase4_dd02
Create Date: 2026-09-24 23:49:59.236791

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'phase5_dd24'
down_revision: str | None = 'phase4_dd02'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mfa_policies',
    sa.Column('subject_type', sa.Enum('USER', 'ROLE', name='mfapolicysubject'), nullable=False, comment='策略主体类型 USER / ROLE'),
    sa.Column('subject_id', sa.BigInteger(), nullable=False, comment='主体 ID（Snowflake）：用户 ID 或角色 ID'),
    sa.Column('required', sa.Boolean(), nullable=True, comment='是否要求 MFA；NULL = 该层未表态（与 False 语义不同，见类文档）'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Snowflake BIGINT 业务主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间 (UTC)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mfa_policies')),
    sa.UniqueConstraint('subject_type', 'subject_id', name='uq_mfa_policies_subject')
    )
    op.create_index('ix_mfa_policies_subject', 'mfa_policies', ['subject_type', 'subject_id'], unique=False)
    op.create_table('mfa_challenges',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户 ID'),
    sa.Column('provider', sa.String(length=32), nullable=False, comment='本次挑战使用的 Provider 名称'),
    sa.Column('token_hash', sa.String(length=64), nullable=False, comment='挑战令牌的 SHA-256 哈希；库内绝不保存明文（与 access/refresh 同口径）'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='过期时间 (UTC)'),
    sa.Column('attempts', sa.SmallInteger(), nullable=False, comment='已失败次数；达到上限即失效（DD-23 Q4，不锁账号）'),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True, comment='核销时间 (UTC)：成功或被判定作废后写入'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Snowflake BIGINT 业务主键'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间 (UTC)'),
    sa.ForeignKeyConstraint(['user_id'], ['admin_users.id'], name=op.f('fk_mfa_challenges_user_id_admin_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mfa_challenges')),
    sa.UniqueConstraint('token_hash', name='uq_mfa_challenges_token_hash')
    )
    op.create_index('ix_mfa_challenges_user_id', 'mfa_challenges', ['user_id'], unique=False)
    op.create_table('user_mfa',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户 ID'),
    sa.Column('provider', sa.String(length=32), nullable=False, comment='MFA Provider 名称（对应 MfaProvider.name）'),
    sa.Column('status', sa.Enum('DISABLED', 'SETUP', 'ENABLED', name='mfastatus'), nullable=False, comment='生命周期状态 DISABLED / SETUP / ENABLED（Spec 04 §6 冻结的三态）'),
    sa.Column('encrypted_secret', sa.Text(), nullable=True, comment='AES-256-GCM 密文 `v1.<base64url(nonce ‖ ct ‖ tag)>`；AAD 绑定 user_id + provider'),
    sa.Column('setup_at', sa.DateTime(timezone=True), nullable=True, comment='进入 SETUP 的时间 (UTC)'),
    sa.Column('enabled_at', sa.DateTime(timezone=True), nullable=True, comment='启用时间 (UTC)'),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True, comment='最近一次校验成功的时间 (UTC)'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Snowflake BIGINT 业务主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间 (UTC)'),
    sa.ForeignKeyConstraint(['user_id'], ['admin_users.id'], name=op.f('fk_user_mfa_user_id_admin_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_mfa')),
    sa.UniqueConstraint('user_id', 'provider', name='uq_user_mfa_user_provider')
    )
    op.create_index('ix_user_mfa_user_id', 'user_mfa', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_mfa_user_id', table_name='user_mfa')
    op.drop_table('user_mfa')
    op.drop_index('ix_mfa_challenges_user_id', table_name='mfa_challenges')
    op.drop_table('mfa_challenges')
    op.drop_index('ix_mfa_policies_subject', table_name='mfa_policies')
    op.drop_table('mfa_policies')
    # ### end Alembic commands ###
