"""phase 3 permission resources role inheritance and versions

Revision ID: phase3_dd20
Revises: phase3_dd07
Create Date: 2026-09-24 13:35:03.159801

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'phase3_dd20'
down_revision: str | None = 'phase3_dd07'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission_resources',
    sa.Column('resource_type', sa.Enum('PAGE', 'MENU', 'BUTTON', 'API', 'FIELD', name='resource_type', native_enum=False, create_constraint=True, length=16), nullable=False, comment='资源类型 PAGE / MENU / BUTTON / API / FIELD（Spec 00 §3）'),
    sa.Column('resource_code', sa.String(length=128), nullable=False, comment='资源编码；业务唯一键，(resource_type, resource_code) 逻辑删除感知唯一'),
    sa.Column('resource_name', sa.String(length=128), nullable=False, comment='资源名称（前端展示）'),
    sa.Column('parent_id', sa.BigInteger(), nullable=True, comment='父资源 ID（权限树）；BUTTON 必须非空，PAGE/API/FIELD 必须为空'),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='同级排序值'),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', name='status', native_enum=False, create_constraint=True, length=16), server_default='ACTIVE', nullable=False, comment='资源状态；DISABLED 的资源不参与有效权限计算'),
    sa.Column('route_path', sa.String(length=255), nullable=True, comment='PAGE 专属：前端路由路径'),
    sa.Column('component_path', sa.String(length=255), nullable=True, comment='PAGE 专属：前端组件路径'),
    sa.Column('icon', sa.String(length=64), nullable=True, comment='MENU 专属：导航图标'),
    sa.Column('api_method', sa.String(length=10), nullable=True, comment='API 专属：HTTP 方法（DD-20 冻结取值域）'),
    sa.Column('api_path', sa.String(length=255), nullable=True, comment='API 专属：接口路径（保留 {id} 占位）；仅作资源台账，不作为判权主键'),
    sa.Column('field_key', sa.String(length=128), nullable=True, comment='FIELD 专属：字段名（如 phone / email）'),
    sa.Column('owner_resource_id', sa.BigInteger(), nullable=True, comment='FIELD 专属：所属 PAGE 资源 ID（应用层保证类型为 PAGE）'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Snowflake BIGINT 业务主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间 (UTC)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='逻辑删除时间 (UTC)，NULL 表示未删除'),
    sa.CheckConstraint("(resource_type <> 'PAGE' OR (parent_id IS NULL AND route_path IS NOT NULL AND component_path IS NOT NULL AND icon IS NULL AND api_method IS NULL AND api_path IS NULL AND field_key IS NULL AND owner_resource_id IS NULL))\n      AND (resource_type <> 'MENU' OR (route_path IS NULL AND component_path IS NULL AND api_method IS NULL AND api_path IS NULL AND field_key IS NULL AND owner_resource_id IS NULL))\n      AND (resource_type <> 'BUTTON' OR (parent_id IS NOT NULL AND route_path IS NULL AND component_path IS NULL AND icon IS NULL AND api_method IS NULL AND api_path IS NULL AND field_key IS NULL AND owner_resource_id IS NULL))\n      AND (resource_type <> 'API' OR (route_path IS NULL AND component_path IS NULL AND icon IS NULL AND api_method IS NOT NULL AND api_path IS NOT NULL AND field_key IS NULL AND owner_resource_id IS NULL))\n      AND (resource_type <> 'FIELD' OR (parent_id IS NULL AND route_path IS NULL AND component_path IS NULL AND icon IS NULL AND api_method IS NULL AND api_path IS NULL AND field_key IS NOT NULL AND owner_resource_id IS NOT NULL))", name=op.f('ck_permission_resources_resource_type_fields')),
    sa.CheckConstraint("api_method IS NULL OR api_method IN ('GET', 'POST', 'PUT', 'PATCH', 'DELETE')", name=op.f('ck_permission_resources_api_method_domain')),
    sa.CheckConstraint('owner_resource_id IS NULL OR owner_resource_id <> id', name=op.f('ck_permission_resources_owner_not_self')),
    sa.CheckConstraint('parent_id IS NULL OR parent_id <> id', name=op.f('ck_permission_resources_parent_not_self')),
    sa.ForeignKeyConstraint(['owner_resource_id'], ['permission_resources.id'], name=op.f('fk_permission_resources_owner_resource_id_permission_resources'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_id'], ['permission_resources.id'], name=op.f('fk_permission_resources_parent_id_permission_resources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permission_resources'))
    )
    op.create_index(op.f('ix_permission_resources_deleted_at'), 'permission_resources', ['deleted_at'], unique=False)
    op.create_index('ix_permission_resources_owner_resource_id_active', 'permission_resources', ['owner_resource_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_permission_resources_parent_id_active', 'permission_resources', ['parent_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_permission_resources_type_status_active', 'permission_resources', ['resource_type', 'status'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('uq_permission_resources_type_code_active', 'permission_resources', ['resource_type', 'resource_code'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('permission_versions',
    sa.Column('scope', sa.String(length=64), nullable=False, comment='版本桶标识；Phase 3 仅使用 GLOBAL（DD-04 未冻结其命名规范）'),
    sa.Column('version', sa.BigInteger(), server_default=sa.text('0'), nullable=False, comment='单调递增版本号'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='最后递增时间 (UTC)'),
    sa.PrimaryKeyConstraint('scope', name=op.f('pk_permission_versions'))
    )
    op.create_table('menu_pages',
    sa.Column('menu_id', sa.BigInteger(), nullable=False, comment='MENU 资源 ID'),
    sa.Column('page_id', sa.BigInteger(), nullable=False, comment='PAGE 资源 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='关联建立时间 (UTC)'),
    sa.ForeignKeyConstraint(['menu_id'], ['permission_resources.id'], name=op.f('fk_menu_pages_menu_id_permission_resources'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['page_id'], ['permission_resources.id'], name=op.f('fk_menu_pages_page_id_permission_resources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('menu_id', 'page_id', name=op.f('pk_menu_pages'))
    )
    op.create_index(op.f('ix_menu_pages_page_id'), 'menu_pages', ['page_id'], unique=False)
    op.create_table('role_field_permissions',
    sa.Column('role_id', sa.BigInteger(), nullable=False, comment='角色 ID'),
    sa.Column('field_id', sa.BigInteger(), nullable=False, comment='FIELD 资源 ID'),
    sa.Column('access_level', sa.Enum('HIDDEN', 'READ_ONLY', 'VISIBLE', 'EDITABLE', name='access_level', native_enum=False, create_constraint=True, length=16), nullable=False, comment='字段权限等级 VISIBLE / HIDDEN / READ_ONLY / EDITABLE'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='授权时间 (UTC)'),
    sa.ForeignKeyConstraint(['field_id'], ['permission_resources.id'], name=op.f('fk_role_field_permissions_field_id_permission_resources'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_field_permissions_role_id_roles'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('role_id', 'field_id', name=op.f('pk_role_field_permissions'))
    )
    op.create_index(op.f('ix_role_field_permissions_field_id'), 'role_field_permissions', ['field_id'], unique=False)
    op.create_table('role_inheritances',
    sa.Column('parent_role_id', sa.BigInteger(), nullable=False, comment='被继承的角色 ID（权限提供方）'),
    sa.Column('child_role_id', sa.BigInteger(), nullable=False, comment='继承的角色 ID（权限获得方）；单独建索引支持按子角色反查'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='继承关系建立时间 (UTC)'),
    sa.CheckConstraint('parent_role_id <> child_role_id', name=op.f('ck_role_inheritances_no_self_inheritance')),
    sa.ForeignKeyConstraint(['child_role_id'], ['roles.id'], name=op.f('fk_role_inheritances_child_role_id_roles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_role_id'], ['roles.id'], name=op.f('fk_role_inheritances_parent_role_id_roles'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('parent_role_id', 'child_role_id', name=op.f('pk_role_inheritances'))
    )
    op.create_index(op.f('ix_role_inheritances_child_role_id'), 'role_inheritances', ['child_role_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.BigInteger(), nullable=False, comment='角色 ID'),
    sa.Column('resource_id', sa.BigInteger(), nullable=False, comment='权限资源 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='授权时间 (UTC)'),
    sa.ForeignKeyConstraint(['resource_id'], ['permission_resources.id'], name=op.f('fk_role_permissions_resource_id_permission_resources'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('role_id', 'resource_id', name=op.f('pk_role_permissions'))
    )
    op.create_index(op.f('ix_role_permissions_resource_id'), 'role_permissions', ['resource_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_role_permissions_resource_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_role_inheritances_child_role_id'), table_name='role_inheritances')
    op.drop_table('role_inheritances')
    op.drop_index(op.f('ix_role_field_permissions_field_id'), table_name='role_field_permissions')
    op.drop_table('role_field_permissions')
    op.drop_index(op.f('ix_menu_pages_page_id'), table_name='menu_pages')
    op.drop_table('menu_pages')
    op.drop_table('permission_versions')
    op.drop_index('uq_permission_resources_type_code_active', table_name='permission_resources', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_permission_resources_type_status_active', table_name='permission_resources', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_permission_resources_parent_id_active', table_name='permission_resources', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_permission_resources_owner_resource_id_active', table_name='permission_resources', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_permission_resources_deleted_at'), table_name='permission_resources')
    op.drop_table('permission_resources')
    # ### end Alembic commands ###
