"""phase15_v31_new_domains

Revision ID: f2ea6e296956
Revises: phase14_notifications
Create Date: 2026-09-30 14:04:04.075404

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
# revision identifiers, used by Alembic.
revision: str = 'f2ea6e296956'
down_revision: str | None = 'phase14_notifications'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biz_cosmetic',
    sa.Column('code', sa.String(length=128), nullable=False, comment='装扮编码；唯一'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='装扮名称'),
    sa.Column('cosmetic_type', sa.Enum('AVATAR', 'AVATAR_FRAME', 'CROWN', 'BADGE', 'TITLE', 'NAME_EFFECT', name='cosmetic_type', native_enum=False, create_constraint=True, length=16), nullable=False, comment='装扮类型 AVATAR/AVATAR_FRAME/CROWN/BADGE/TITLE/NAME_EFFECT'),
    sa.Column('image_url', sa.String(length=512), nullable=True, comment='图片 URL'),
    sa.Column('animation_url', sa.String(length=512), nullable=True, comment='动画 URL'),
    sa.Column('rarity', sa.String(length=32), nullable=True, comment='稀有度；取值域待冻结'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='状态；取值域待冻结'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='描述'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Snowflake BIGINT 业务主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间 (UTC)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='逻辑删除时间 (UTC)，NULL 表示未删除'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_biz_cosmetic'))
    )
    op.create_index(op.f('ix_biz_cosmetic_deleted_at'), 'biz_cosmetic', ['deleted_at'], unique=False)
    op.create_index('uq_biz_cosmetic_code_active', 'biz_cosmetic', ['code'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('biz_growth_event',
    sa.Column('event_id', sa.String(length=128), nullable=False, comment='业务事件 ID；唯一'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='业务用户 ID'),
    sa.Column('source_type', sa.String(length=64), nullable=False, comment='来源类型；取值域待冻结'),
    sa.Column('source_id', sa.String(length=128), nullable=True, comment='来源 ID'),
    sa.Column('event_type', sa.String(length=128), nullable=False, comment='事件类型；取值域待冻结'),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False, comment='幂等键；唯一'),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='事件载荷（禁止写入敏感业务内容）'),
    sa.Column('processed', sa.Boolean(), nullable=False, comment='是否已处理'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True, comment='处理时间 (UTC)'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Snowflake BIGINT 业务主键'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_biz_growth_event')),
    sa.UniqueConstraint('event_id', name='uq_biz_growth_event_id'),
    sa.UniqueConstraint('idempotency_key', name='uq_biz_growth_event_idempotency')
    )
    op.create_index('ix_biz_growth_event_type_time', 'biz_growth_event', ['event_type', 'created_at'], unique=False)
    op.create_index('ix_biz_growth_event_user_time', 'biz_growth_event', ['user_id', 'created_at'], unique=False)
    op.create_table('biz_growth_rule',
    sa.Column('code', sa.String(length=64), nullable=False, comment='规则编码；唯一'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='规则名称'),
    sa.Column('source_type', sa.String(length=64), nullable=False, comment='来源类型；取值域待冻结'),
    sa.Column('event_type', sa.String(length=128), nullable=False, comment='事件类型；取值域待冻结'),
    sa.Column('reward_points', sa.BigInteger(), nullable=False, comment='奖励成长值'),
    sa.Column('daily_limit', sa.BigInteger(), nullable=True, comment='每日上限（次）'),
    sa.Column('weekly_limit', sa.BigInteger(), nullable=True, comment='每周上限（次）'),
    sa.Column('monthly_limit', sa.BigInteger(), nullable=True, comment='每月上限（次）'),
    sa.Column('cooldown_seconds', sa.Integer(), nullable=True, comment='冷却秒数'),
    sa.Column('requires_success', sa.Boolean(), nullable=False, comment='是否要求业务成功才奖励'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='状态；取值域待冻结'),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True, comment='生效开始 (UTC)'),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True, comment='生效结束 (UTC)'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='规则描述'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Snowflake BIGINT 业务主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间 (UTC)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_biz_growth_rule')),
    sa.UniqueConstraint('code', name='uq_biz_growth_rule_code')
    )
    op.create_table('biz_point_rule',
    sa.Column('code', sa.String(length=64), nullable=False, comment='规则编码；唯一'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='规则名称'),
    sa.Column('source_type', sa.String(length=64), nullable=False, comment='来源类型；取值域待冻结'),
    sa.Column('event_type', sa.String(length=128), nullable=False, comment='事件类型；取值域待冻结'),
    sa.Column('reward_points', sa.BigInteger(), nullable=False, comment='奖励积分'),
    sa.Column('daily_limit', sa.BigInteger(), nullable=True, comment='每日上限（次）'),
    sa.Column('weekly_limit', sa.BigInteger(), nullable=True, comment='每周上限（次）'),
    sa.Column('monthly_limit', sa.BigInteger(), nullable=True, comment='每月上限（次）'),
    sa.Column('cooldown_seconds', sa.Integer(), nullable=True, comment='冷却秒数'),
    sa.Column('requires_success', sa.Boolean(), nullable=False, comment='是否要求业务成功才奖励'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='状态；取值域待冻结'),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True, comment='生效开始 (UTC)'),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True, comment='生效结束 (UTC)'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='规则描述'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Snowflake BIGINT 业务主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间 (UTC)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_biz_point_rule')),
    sa.UniqueConstraint('code', name='uq_biz_point_rule_code')
    )
    op.create_table('biz_task',
    sa.Column('code', sa.String(length=64), nullable=False, comment='任务编码；唯一'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='任务名称'),
    sa.Column('task_type', sa.String(length=64), nullable=False, comment='任务类型；取值域待冻结'),
    sa.Column('target_value', sa.BigInteger(), nullable=True, comment='目标值'),
    sa.Column('reward_growth_points', sa.BigInteger(), nullable=False, comment='奖励成长值'),
    sa.Column('reward_points', sa.BigInteger(), nullable=False, comment='奖励积分'),
    sa.Column('repeat_type', sa.String(length=32), nullable=False, comment='重复类型；取值域待冻结'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='状态；取值域待冻结'),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True, comment='生效开始 (UTC)'),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True, comment='生效结束 (UTC)'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Snowflake BIGINT 业务主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间 (UTC)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_biz_task')),
    sa.UniqueConstraint('code', name='uq_biz_task_code')
    )
    op.create_table('biz_user_level',
    sa.Column('code', sa.String(length=64), nullable=False, comment='等级编码；逻辑删除感知唯一'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='等级名称'),
    sa.Column('level_value', sa.Integer(), nullable=False, comment='等级数值；唯一，用于排序与判定'),
    sa.Column('required_growth_points', sa.BigInteger(), nullable=False, comment='升级到该等级所需的成长值'),
    sa.Column('icon_url', sa.String(length=512), nullable=True, comment='等级图标 URL'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='状态；取值域待冻结'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='等级描述'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Snowflake BIGINT 业务主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间 (UTC)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='逻辑删除时间 (UTC)，NULL 表示未删除'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_biz_user_level'))
    )
    op.create_index(op.f('ix_biz_user_level_deleted_at'), 'biz_user_level', ['deleted_at'], unique=False)
    op.create_index('uq_biz_user_level_code_active', 'biz_user_level', ['code'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('uq_biz_user_level_value_active', 'biz_user_level', ['level_value'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('biz_user_point_account',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='业务用户 ID（唯一）'),
    sa.Column('total_earned_points', sa.BigInteger(), nullable=False, comment='累计获得积分'),
    sa.Column('total_spent_points', sa.BigInteger(), nullable=False, comment='累计消费积分'),
    sa.Column('balance_points', sa.BigInteger(), nullable=False, comment='可用余额积分'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Snowflake BIGINT 业务主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间 (UTC)'),
    sa.CheckConstraint('balance_points >= 0', name=op.f('ck_biz_user_point_account_balance_non_negative')),
    sa.CheckConstraint('total_earned_points >= 0', name=op.f('ck_biz_user_point_account_earned_non_negative')),
    sa.CheckConstraint('total_spent_points >= 0', name=op.f('ck_biz_user_point_account_spent_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_biz_user_point_account')),
    sa.UniqueConstraint('user_id', name=op.f('uq_biz_user_point_account_user_id'))
    )
    op.create_table('biz_user_profile',
    sa.Column('user_id', sa.BigInteger(), autoincrement=False, nullable=False, comment='业务用户 ID'),
    sa.Column('nickname', sa.String(length=128), nullable=True, comment='昵称'),
    sa.Column('avatar_url', sa.String(length=512), nullable=True, comment='头像 URL'),
    sa.Column('bio', sa.String(length=1000), nullable=True, comment='个人简介'),
    sa.Column('gender', sa.String(length=32), nullable=True, comment='性别；取值域待冻结'),
    sa.Column('birthday', sa.Date(), nullable=True, comment='生日'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Snowflake BIGINT 业务主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间 (UTC)'),
    sa.PrimaryKeyConstraint('user_id', 'id', name=op.f('pk_biz_user_profile'))
    )
    op.create_table('blog_category',
    sa.Column('parent_id', sa.BigInteger(), nullable=True, comment='父分类 ID；NULL 表示根分类'),
    sa.Column('code', sa.String(length=64), nullable=False, comment='分类编码；唯一'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='分类名称'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='状态；取值域待冻结'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Snowflake BIGINT 业务主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间 (UTC)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='逻辑删除时间 (UTC)，NULL 表示未删除'),
    sa.ForeignKeyConstraint(['parent_id'], ['blog_category.id'], name=op.f('fk_blog_category_parent_id_blog_category'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_category'))
    )
    op.create_index(op.f('ix_blog_category_deleted_at'), 'blog_category', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_blog_category_parent_id'), 'blog_category', ['parent_id'], unique=False)
    op.create_index('uq_blog_category_code_active', 'blog_category', ['code'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('blog_tag',
    sa.Column('code', sa.String(length=64), nullable=False, comment='标签编码；唯一'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='标签名称'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='状态；取值域待冻结'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Snowflake BIGINT 业务主键'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_tag')),
    sa.UniqueConstraint('code', name='uq_blog_tag_code')
    )
    op.create_table('tool_category',
    sa.Column('parent_id', sa.BigInteger(), nullable=True, comment='父分类 ID；NULL 表示根分类'),
    sa.Column('code', sa.String(length=64), nullable=False, comment='分类编码；唯一'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='分类名称'),
    sa.Column('icon_url', sa.String(length=512), nullable=True, comment='图标 URL'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='状态；取值域待冻结'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Snowflake BIGINT 业务主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间 (UTC)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='逻辑删除时间 (UTC)，NULL 表示未删除'),
    sa.ForeignKeyConstraint(['parent_id'], ['tool_category.id'], name=op.f('fk_tool_category_parent_id_tool_category'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool_category'))
    )
    op.create_index(op.f('ix_tool_category_deleted_at'), 'tool_category', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_tool_category_parent_id'), 'tool_category', ['parent_id'], unique=False)
    op.create_index('uq_tool_category_code_active', 'tool_category', ['code'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('tool_component_registry',
    sa.Column('component_key', sa.String(length=128), nullable=False, comment='组件键；唯一'),
    sa.Column('component_type', sa.String(length=32), nullable=False, comment='组件类型；取值域待冻结'),
    sa.Column('implementation_ref', sa.String(length=255), nullable=False, comment='受控实现引用'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='状态；取值域待冻结'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Snowflake BIGINT 业务主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间 (UTC)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool_component_registry')),
    sa.UniqueConstraint('component_key', name='uq_tool_component_registry_key')
    )
    op.create_table('tool_popularity_daily',
    sa.Column('tool_id', sa.BigInteger(), nullable=False, comment='工具 ID'),
    sa.Column('stat_date', sa.Date(), nullable=False, comment='统计日期'),
    sa.Column('score', sa.Numeric(precision=20, scale=6), nullable=False, comment='热门得分'),
    sa.Column('rank_no', sa.Integer(), nullable=True, comment='当日排名'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Snowflake BIGINT 业务主键'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool_popularity_daily')),
    sa.UniqueConstraint('tool_id', 'stat_date', name='uq_tool_popularity_daily_tool_date')
    )
    op.create_table('tool_usage_daily',
    sa.Column('tool_id', sa.BigInteger(), nullable=False, comment='工具 ID'),
    sa.Column('stat_date', sa.Date(), nullable=False, comment='统计日期'),
    sa.Column('total_count', sa.BigInteger(), nullable=False, comment='总次数'),
    sa.Column('success_count', sa.BigInteger(), nullable=False, comment='成功次数'),
    sa.Column('failure_count', sa.BigInteger(), nullable=False, comment='失败次数'),
    sa.Column('guest_count', sa.BigInteger(), nullable=False, comment='游客次数'),
    sa.Column('user_count', sa.BigInteger(), nullable=False, comment='登录用户次数'),
    sa.Column('unique_user_count', sa.BigInteger(), nullable=False, comment='独立用户数'),
    sa.Column('avg_duration_ms', sa.Numeric(precision=18, scale=2), nullable=True, comment='平均耗时（毫秒）'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Snowflake BIGINT 业务主键'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool_usage_daily')),
    sa.UniqueConstraint('tool_id', 'stat_date', name='uq_tool_usage_daily_tool_date')
    )
    op.create_table('biz_achievement',
    sa.Column('code', sa.String(length=64), nullable=False, comment='成就编码；唯一'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='成就名称'),
    sa.Column('icon_url', sa.String(length=512), nullable=True, comment='图标 URL'),
    sa.Column('achievement_type', sa.String(length=64), nullable=False, comment='成就类型；取值域待冻结'),
    sa.Column('target_value', sa.BigInteger(), nullable=True, comment='目标值'),
    sa.Column('reward_growth_points', sa.BigInteger(), nullable=False, comment='奖励成长值'),
    sa.Column('reward_points', sa.BigInteger(), nullable=False, comment='奖励积分'),
    sa.Column('reward_cosmetic_id', sa.BigInteger(), nullable=True, comment='奖励装扮 ID'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='状态；取值域待冻结'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Snowflake BIGINT 业务主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间 (UTC)'),
    sa.ForeignKeyConstraint(['reward_cosmetic_id'], ['biz_cosmetic.id'], name=op.f('fk_biz_achievement_reward_cosmetic_id_biz_cosmetic'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_biz_achievement')),
    sa.UniqueConstraint('code', name='uq_biz_achievement_code')
    )
    op.create_table('biz_user',
    sa.Column('username', sa.String(length=64), nullable=False, comment='业务用户名；逻辑删除感知唯一'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='状态；取值域待冻结'),
    sa.Column('user_level_id', sa.BigInteger(), nullable=True, comment='当前等级 ID'),
    sa.Column('must_change_password', sa.Boolean(), nullable=False, comment='是否必须修改初始口令'),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True, comment='口令最近修改时间 (UTC)'),
    sa.Column('password_expires_at', sa.DateTime(timezone=True), nullable=True, comment='口令过期时间 (UTC)'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='最近登录时间 (UTC)'),
    sa.Column('last_login_ip', postgresql.INET(), nullable=True, comment='最近登录 IP'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Snowflake BIGINT 业务主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间 (UTC)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='逻辑删除时间 (UTC)，NULL 表示未删除'),
    sa.ForeignKeyConstraint(['user_level_id'], ['biz_user_level.id'], name=op.f('fk_biz_user_user_level_id_biz_user_level'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_biz_user'))
    )
    op.create_index(op.f('ix_biz_user_deleted_at'), 'biz_user', ['deleted_at'], unique=False)
    op.create_index('uq_biz_user_username_active', 'biz_user', ['username'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('biz_user_cosmetic',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='业务用户 ID'),
    sa.Column('cosmetic_id', sa.BigInteger(), nullable=False, comment='装扮 ID'),
    sa.Column('source_type', sa.String(length=64), nullable=False, comment='获取来源类型；取值域待冻结'),
    sa.Column('source_id', sa.String(length=128), nullable=True, comment='获取来源 ID'),
    sa.Column('acquired_at', sa.DateTime(timezone=True), nullable=False, comment='获取时间 (UTC)'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Snowflake BIGINT 业务主键'),
    sa.ForeignKeyConstraint(['cosmetic_id'], ['biz_cosmetic.id'], name=op.f('fk_biz_user_cosmetic_cosmetic_id_biz_cosmetic'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_biz_user_cosmetic')),
    sa.UniqueConstraint('user_id', 'cosmetic_id', name='uq_user_cosmetic_owned')
    )
    op.create_table('biz_user_equipment',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='业务用户 ID（唯一）'),
    sa.Column('avatar_cosmetic_id', sa.BigInteger(), nullable=True, comment='头像装扮 ID'),
    sa.Column('avatar_frame_cosmetic_id', sa.BigInteger(), nullable=True, comment='头像框装扮 ID'),
    sa.Column('crown_cosmetic_id', sa.BigInteger(), nullable=True, comment='皇冠装扮 ID'),
    sa.Column('badge_cosmetic_id', sa.BigInteger(), nullable=True, comment='徽章装扮 ID'),
    sa.Column('title_cosmetic_id', sa.BigInteger(), nullable=True, comment='头衔装扮 ID'),
    sa.Column('name_effect_cosmetic_id', sa.BigInteger(), nullable=True, comment='昵称特效装扮 ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间 (UTC)'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Snowflake BIGINT 业务主键'),
    sa.ForeignKeyConstraint(['avatar_cosmetic_id'], ['biz_cosmetic.id'], name=op.f('fk_biz_user_equipment_avatar_cosmetic_id_biz_cosmetic'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['avatar_frame_cosmetic_id'], ['biz_cosmetic.id'], name=op.f('fk_biz_user_equipment_avatar_frame_cosmetic_id_biz_cosmetic'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['badge_cosmetic_id'], ['biz_cosmetic.id'], name=op.f('fk_biz_user_equipment_badge_cosmetic_id_biz_cosmetic'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['crown_cosmetic_id'], ['biz_cosmetic.id'], name=op.f('fk_biz_user_equipment_crown_cosmetic_id_biz_cosmetic'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['name_effect_cosmetic_id'], ['biz_cosmetic.id'], name=op.f('fk_biz_user_equipment_name_effect_cosmetic_id_biz_cosmetic'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['title_cosmetic_id'], ['biz_cosmetic.id'], name=op.f('fk_biz_user_equipment_title_cosmetic_id_biz_cosmetic'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_biz_user_equipment')),
    sa.UniqueConstraint('user_id', name=op.f('uq_biz_user_equipment_user_id'))
    )
    op.create_table('biz_user_growth_account',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='业务用户 ID（唯一）'),
    sa.Column('total_growth_points', sa.BigInteger(), nullable=False, comment='累计成长值'),
    sa.Column('current_level_id', sa.BigInteger(), nullable=True, comment='当前等级 ID'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Snowflake BIGINT 业务主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间 (UTC)'),
    sa.ForeignKeyConstraint(['current_level_id'], ['biz_user_level.id'], name=op.f('fk_biz_user_growth_account_current_level_id_biz_user_level'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_biz_user_growth_account')),
    sa.UniqueConstraint('user_id', name=op.f('uq_biz_user_growth_account_user_id'))
    )
    op.create_table('biz_user_growth_transaction',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='业务用户 ID'),
    sa.Column('change_points', sa.BigInteger(), nullable=False, comment='变动成长值（负为扣减）'),
    sa.Column('balance_after', sa.BigInteger(), nullable=False, comment='变动后余额'),
    sa.Column('rule_id', sa.BigInteger(), nullable=True, comment='关联规则 ID'),
    sa.Column('source_type', sa.String(length=64), nullable=False, comment='来源类型；取值域待冻结'),
    sa.Column('source_id', sa.String(length=128), nullable=True, comment='来源 ID'),
    sa.Column('event_id', sa.String(length=128), nullable=True, comment='关联事件 ID'),
    sa.Column('transaction_type', sa.String(length=32), nullable=False, comment='流水类型；取值域待冻结'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='描述'),
    sa.Column('operator_type', sa.String(length=32), nullable=False, comment='操作主体类型；取值域待冻结'),
    sa.Column('operator_id', sa.BigInteger(), nullable=True, comment='操作主体 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Snowflake BIGINT 业务主键'),
    sa.ForeignKeyConstraint(['rule_id'], ['biz_growth_rule.id'], name=op.f('fk_biz_user_growth_transaction_rule_id_biz_growth_rule'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_biz_user_growth_transaction'))
    )
    op.create_index('idx_biz_growth_tx_user_time', 'biz_user_growth_transaction', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('biz_user_level_benefit',
    sa.Column('level_id', sa.BigInteger(), nullable=False, comment='等级 ID'),
    sa.Column('benefit_type', sa.String(length=64), nullable=False, comment='权益类型；取值域待冻结'),
    sa.Column('benefit_code', sa.String(length=128), nullable=False, comment='权益编码'),
    sa.Column('benefit_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='权益配置'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='状态；取值域待冻结'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Snowflake BIGINT 业务主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间 (UTC)'),
    sa.ForeignKeyConstraint(['level_id'], ['biz_user_level.id'], name=op.f('fk_biz_user_level_benefit_level_id_biz_user_level'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_biz_user_level_benefit'))
    )
    op.create_index('ix_biz_user_level_benefit_level', 'biz_user_level_benefit', ['level_id'], unique=False)
    op.create_table('biz_user_level_history',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='业务用户 ID'),
    sa.Column('from_level_id', sa.BigInteger(), nullable=True, comment='原等级 ID'),
    sa.Column('to_level_id', sa.BigInteger(), nullable=False, comment='目标等级 ID'),
    sa.Column('growth_points', sa.BigInteger(), nullable=False, comment='当时成长值'),
    sa.Column('change_type', sa.String(length=32), nullable=False, comment='变动类型；取值域待冻结'),
    sa.Column('reason', sa.String(length=500), nullable=True, comment='变动原因'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Snowflake BIGINT 业务主键'),
    sa.ForeignKeyConstraint(['from_level_id'], ['biz_user_level.id'], name=op.f('fk_biz_user_level_history_from_level_id_biz_user_level'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_level_id'], ['biz_user_level.id'], name=op.f('fk_biz_user_level_history_to_level_id_biz_user_level'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_biz_user_level_history'))
    )
    op.create_table('biz_user_point_transaction',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='业务用户 ID'),
    sa.Column('change_points', sa.BigInteger(), nullable=False, comment='变动积分（负为扣减）'),
    sa.Column('balance_after', sa.BigInteger(), nullable=False, comment='变动后余额'),
    sa.Column('rule_id', sa.BigInteger(), nullable=True, comment='关联规则 ID'),
    sa.Column('source_type', sa.String(length=64), nullable=False, comment='来源类型；取值域待冻结'),
    sa.Column('source_id', sa.String(length=128), nullable=True, comment='来源 ID'),
    sa.Column('event_id', sa.String(length=128), nullable=True, comment='关联事件 ID'),
    sa.Column('transaction_type', sa.String(length=32), nullable=False, comment='流水类型；取值域待冻结'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='描述'),
    sa.Column('operator_type', sa.String(length=32), nullable=False, comment='操作主体类型；取值域待冻结'),
    sa.Column('operator_id', sa.BigInteger(), nullable=True, comment='操作主体 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Snowflake BIGINT 业务主键'),
    sa.ForeignKeyConstraint(['rule_id'], ['biz_point_rule.id'], name=op.f('fk_biz_user_point_transaction_rule_id_biz_point_rule'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_biz_user_point_transaction'))
    )
    op.create_index('idx_biz_point_tx_user_time', 'biz_user_point_transaction', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('biz_user_task',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='业务用户 ID'),
    sa.Column('task_id', sa.BigInteger(), nullable=False, comment='任务 ID'),
    sa.Column('progress', sa.BigInteger(), nullable=False, comment='当前进度'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='任务状态；取值域待冻结'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='完成时间 (UTC)'),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True, comment='领取奖励时间 (UTC)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Snowflake BIGINT 业务主键'),
    sa.ForeignKeyConstraint(['task_id'], ['biz_task.id'], name=op.f('fk_biz_user_task_task_id_biz_task'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_biz_user_task')),
    sa.UniqueConstraint('user_id', 'task_id', name='uq_biz_user_task_user')
    )
    op.create_table('tool',
    sa.Column('category_id', sa.BigInteger(), nullable=False, comment='所属分类 ID'),
    sa.Column('code', sa.String(length=128), nullable=False, comment='工具编码；唯一'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='工具名称'),
    sa.Column('description', sa.String(length=1000), nullable=True, comment='工具描述'),
    sa.Column('component_key', sa.String(length=128), nullable=True, comment='组件键；映射到受控实现（见 §4）'),
    sa.Column('execution_mode', sa.Enum('FRONTEND', 'BACKEND', 'ASYNC', name='execution_mode', native_enum=False, create_constraint=True, length=16), nullable=False, comment='执行模式 FRONTEND / BACKEND / ASYNC'),
    sa.Column('lifecycle_status', sa.Enum('DRAFT', 'TESTING', 'ACTIVE', 'DISABLED', name='lifecycle_status', native_enum=False, create_constraint=True, length=16), nullable=False, comment='生命周期 DRAFT / TESTING / ACTIVE / DISABLED'),
    sa.Column('visibility', sa.String(length=32), nullable=False, comment='可见性；取值域待冻结'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('is_recommended', sa.Boolean(), nullable=False, comment='是否推荐'),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='标签集合'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Snowflake BIGINT 业务主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间 (UTC)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='逻辑删除时间 (UTC)，NULL 表示未删除'),
    sa.ForeignKeyConstraint(['category_id'], ['tool_category.id'], name=op.f('fk_tool_category_id_tool_category'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool'))
    )
    op.create_index(op.f('ix_tool_deleted_at'), 'tool', ['deleted_at'], unique=False)
    op.create_index('uq_tool_code_active', 'tool', ['code'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('biz_user_achievement',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='业务用户 ID'),
    sa.Column('achievement_id', sa.BigInteger(), nullable=False, comment='成就 ID'),
    sa.Column('progress', sa.BigInteger(), nullable=False, comment='当前进度'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='完成时间 (UTC)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Snowflake BIGINT 业务主键'),
    sa.ForeignKeyConstraint(['achievement_id'], ['biz_achievement.id'], name=op.f('fk_biz_user_achievement_achievement_id_biz_achievement'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_biz_user_achievement')),
    sa.UniqueConstraint('user_id', 'achievement_id', name='uq_biz_user_achievement_user')
    )
    op.create_table('biz_user_login_identity',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='所属业务用户 ID'),
    sa.Column('identity_type', sa.Enum('USERNAME', 'EMAIL', 'PHONE', name='identity_type', native_enum=False, create_constraint=True, length=16), nullable=False, comment='身份类型 USERNAME / EMAIL / PHONE'),
    sa.Column('normalized_value', sa.String(length=255), nullable=False, comment='归一化后的身份值（小写 / 去格式）'),
    sa.Column('verified', sa.Boolean(), nullable=False, comment='是否已验证'),
    sa.Column('is_primary', sa.Boolean(), nullable=False, comment='是否主身份'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Snowflake BIGINT 业务主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间 (UTC)'),
    sa.ForeignKeyConstraint(['user_id'], ['biz_user.id'], name=op.f('fk_biz_user_login_identity_user_id_biz_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_biz_user_login_identity')),
    sa.UniqueConstraint('identity_type', 'normalized_value', name='uq_biz_user_login_identity_type_value')
    )
    op.create_table('biz_user_login_log',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='业务用户 ID'),
    sa.Column('success', sa.Boolean(), nullable=False, comment='是否登录成功'),
    sa.Column('fail_reason', sa.String(length=255), nullable=True, comment='失败原因'),
    sa.Column('ip', postgresql.INET(), nullable=True, comment='登录 IP'),
    sa.Column('user_agent', sa.String(length=1000), nullable=True, comment='用户代理'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Snowflake BIGINT 业务主键'),
    sa.ForeignKeyConstraint(['user_id'], ['biz_user.id'], name=op.f('fk_biz_user_login_log_user_id_biz_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_biz_user_login_log'))
    )
    op.create_table('biz_user_password_history',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='业务用户 ID'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='历史口令哈希'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Snowflake BIGINT 业务主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间 (UTC)'),
    sa.ForeignKeyConstraint(['user_id'], ['biz_user.id'], name=op.f('fk_biz_user_password_history_user_id_biz_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_biz_user_password_history'))
    )
    op.create_table('biz_user_session',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='业务用户 ID'),
    sa.Column('session_id', sa.String(length=128), nullable=False, comment='会话 ID；唯一'),
    sa.Column('ip', postgresql.INET(), nullable=True, comment='登录 IP'),
    sa.Column('user_agent', sa.String(length=1000), nullable=True, comment='用户代理'),
    sa.Column('login_at', sa.DateTime(timezone=True), nullable=False, comment='登录时间 (UTC)'),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True, comment='最近活跃时间 (UTC)'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='过期时间 (UTC)'),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True, comment='撤销时间 (UTC)'),
    sa.Column('revoke_reason', sa.String(length=255), nullable=True, comment='撤销原因'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Snowflake BIGINT 业务主键'),
    sa.ForeignKeyConstraint(['user_id'], ['biz_user.id'], name=op.f('fk_biz_user_session_user_id_biz_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_biz_user_session')),
    sa.UniqueConstraint('session_id', name='uq_biz_user_session_id')
    )
    op.create_table('biz_user_verification',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='业务用户 ID'),
    sa.Column('identity_type', sa.String(length=32), nullable=False, comment='验证类型 EMAIL / PHONE / 等；取值域待冻结'),
    sa.Column('token_hash', sa.String(length=255), nullable=False, comment='验证令牌哈希（不存明文令牌）'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='过期时间 (UTC)'),
    sa.Column('verified', sa.Boolean(), nullable=False, comment='是否已验证'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Snowflake BIGINT 业务主键'),
    sa.ForeignKeyConstraint(['user_id'], ['biz_user.id'], name=op.f('fk_biz_user_verification_user_id_biz_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_biz_user_verification'))
    )
    op.create_table('blog_author',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='业务用户 ID（唯一）'),
    sa.Column('author_name', sa.String(length=128), nullable=False, comment='作者名'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='状态；取值域待冻结'),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True, comment='审核通过时间 (UTC)'),
    sa.Column('approved_by', sa.BigInteger(), nullable=True, comment='审核人（管理员）ID'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Snowflake BIGINT 业务主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间 (UTC)'),
    sa.ForeignKeyConstraint(['approved_by'], ['admin_users.id'], name=op.f('fk_blog_author_approved_by_admin_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_author')),
    sa.UniqueConstraint('user_id', name=op.f('uq_blog_author_user_id'))
    )
    op.create_table('blog_author_application',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='申请人（业务用户）ID'),
    sa.Column('application_reason', sa.String(length=2000), nullable=True, comment='申请理由'),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='status', native_enum=False, create_constraint=True, length=16), nullable=False, comment='申请状态 PENDING / APPROVED / REJECTED'),
    sa.Column('reviewed_by', sa.BigInteger(), nullable=True, comment='审核人（管理员）ID'),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True, comment='审核时间 (UTC)'),
    sa.Column('review_remark', sa.String(length=1000), nullable=True, comment='审核备注'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Snowflake BIGINT 业务主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间 (UTC)'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['admin_users.id'], name=op.f('fk_blog_author_application_reviewed_by_admin_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['biz_user.id'], name=op.f('fk_blog_author_application_user_id_biz_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_author_application'))
    )
    op.create_table('blog_user_follow',
    sa.Column('follower_user_id', sa.BigInteger(), nullable=False, comment='关注者（业务用户）ID'),
    sa.Column('followed_user_id', sa.BigInteger(), nullable=False, comment='被关注者（业务用户）ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Snowflake BIGINT 业务主键'),
    sa.CheckConstraint('follower_user_id <> followed_user_id', name=op.f('ck_blog_user_follow_follower_not_self')),
    sa.ForeignKeyConstraint(['followed_user_id'], ['biz_user.id'], name=op.f('fk_blog_user_follow_followed_user_id_biz_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['follower_user_id'], ['biz_user.id'], name=op.f('fk_blog_user_follow_follower_user_id_biz_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('follower_user_id', 'followed_user_id', 'id', name=op.f('pk_blog_user_follow'))
    )
    op.create_table('tool_access_policy',
    sa.Column('tool_id', sa.BigInteger(), nullable=False, comment='所属工具 ID'),
    sa.Column('subject_type', sa.Enum('GUEST', 'USER_LEVEL', name='subject_type', native_enum=False, create_constraint=True, length=16), nullable=False, comment='主体类型 GUEST / USER_LEVEL'),
    sa.Column('user_level_id', sa.BigInteger(), nullable=True, comment='USER_LEVEL 主体对应的等级 ID'),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('quota_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='额度配置'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Snowflake BIGINT 业务主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间 (UTC)'),
    sa.ForeignKeyConstraint(['tool_id'], ['tool.id'], name=op.f('fk_tool_access_policy_tool_id_tool'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_level_id'], ['biz_user_level.id'], name=op.f('fk_tool_access_policy_user_level_id_biz_user_level'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool_access_policy'))
    )
    op.create_table('tool_recent_usage',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='业务用户 ID'),
    sa.Column('tool_id', sa.BigInteger(), nullable=False, comment='工具 ID'),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=False, comment='最近使用时间 (UTC)'),
    sa.Column('use_count', sa.BigInteger(), nullable=False, comment='使用次数'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Snowflake BIGINT 业务主键'),
    sa.ForeignKeyConstraint(['tool_id'], ['tool.id'], name=op.f('fk_tool_recent_usage_tool_id_tool'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['biz_user.id'], name=op.f('fk_tool_recent_usage_user_id_biz_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool_recent_usage')),
    sa.UniqueConstraint('user_id', 'tool_id', name='uq_tool_recent_usage_user')
    )
    op.create_table('tool_usage_event',
    sa.Column('tool_id', sa.BigInteger(), nullable=False, comment='工具 ID'),
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='业务用户 ID；游客为 NULL'),
    sa.Column('anonymous_id_hash', sa.String(length=128), nullable=True, comment='游客匿名 ID 哈希'),
    sa.Column('result', sa.String(length=32), nullable=True, comment='执行结果；取值域待冻结'),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True, comment='耗时（毫秒）'),
    sa.Column('execution_mode', sa.String(length=32), nullable=True, comment='执行模式；取值域待冻结'),
    sa.Column('trace_id', sa.String(length=128), nullable=True, comment='链路追踪 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Snowflake BIGINT 业务主键'),
    sa.ForeignKeyConstraint(['user_id'], ['biz_user.id'], name=op.f('fk_tool_usage_event_user_id_biz_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool_usage_event'))
    )
    op.create_index('idx_tool_usage_tool_time', 'tool_usage_event', ['tool_id', 'created_at'], unique=False)
    op.create_table('tool_version',
    sa.Column('tool_id', sa.BigInteger(), nullable=False, comment='所属工具 ID'),
    sa.Column('version', sa.String(length=64), nullable=False, comment='版本号'),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='版本配置'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='版本状态；取值域待冻结'),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True, comment='发布时间 (UTC)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Snowflake BIGINT 业务主键'),
    sa.ForeignKeyConstraint(['tool_id'], ['tool.id'], name=op.f('fk_tool_version_tool_id_tool'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool_version')),
    sa.UniqueConstraint('tool_id', 'version', name='uq_tool_version_tool')
    )
    op.create_table('blog_article',
    sa.Column('author_id', sa.BigInteger(), nullable=False, comment='作者 ID'),
    sa.Column('category_id', sa.BigInteger(), nullable=True, comment='分类 ID'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='标题'),
    sa.Column('slug', sa.String(length=255), nullable=False, comment='URL 别名；唯一'),
    sa.Column('summary', sa.String(length=1000), nullable=True, comment='摘要'),
    sa.Column('cover_url', sa.String(length=512), nullable=True, comment='封面 URL'),
    sa.Column('content', sa.Text(), nullable=False, comment='正文'),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_REVIEW', 'REJECTED', 'PUBLISHED', 'OFFLINE', name='status', native_enum=False, create_constraint=True, length=16), nullable=False, comment='文章状态 DRAFT/PENDING_REVIEW/REJECTED/PUBLISHED/OFFLINE'),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True, comment='发布时间 (UTC)'),
    sa.Column('view_count', sa.BigInteger(), nullable=False, comment='浏览数'),
    sa.Column('like_count', sa.BigInteger(), nullable=False, comment='点赞数'),
    sa.Column('favorite_count', sa.BigInteger(), nullable=False, comment='收藏数'),
    sa.Column('comment_count', sa.BigInteger(), nullable=False, comment='评论数'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Snowflake BIGINT 业务主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间 (UTC)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='逻辑删除时间 (UTC)，NULL 表示未删除'),
    sa.ForeignKeyConstraint(['author_id'], ['blog_author.id'], name=op.f('fk_blog_article_author_id_blog_author'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['category_id'], ['blog_category.id'], name=op.f('fk_blog_article_category_id_blog_category'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_article'))
    )
    op.create_index('ix_blog_article_author_status', 'blog_article', ['author_id', 'status'], unique=False)
    op.create_index(op.f('ix_blog_article_deleted_at'), 'blog_article', ['deleted_at'], unique=False)
    op.create_index('uq_blog_article_slug_active', 'blog_article', ['slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('blog_article_tag',
    sa.Column('article_id', sa.BigInteger(), nullable=False, comment='文章 ID'),
    sa.Column('tag_id', sa.BigInteger(), nullable=False, comment='标签 ID'),
    sa.ForeignKeyConstraint(['article_id'], ['blog_article.id'], name=op.f('fk_blog_article_tag_article_id_blog_article'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tag_id'], ['blog_tag.id'], name=op.f('fk_blog_article_tag_tag_id_blog_tag'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('article_id', 'tag_id', name=op.f('pk_blog_article_tag'))
    )
    op.create_table('blog_article_version',
    sa.Column('article_id', sa.BigInteger(), nullable=False, comment='文章 ID'),
    sa.Column('version_no', sa.Integer(), nullable=False, comment='版本号'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='标题'),
    sa.Column('summary', sa.String(length=1000), nullable=True, comment='摘要'),
    sa.Column('content', sa.Text(), nullable=False, comment='正文'),
    sa.Column('created_by', sa.BigInteger(), nullable=False, comment='创建人（管理员）ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Snowflake BIGINT 业务主键'),
    sa.ForeignKeyConstraint(['article_id'], ['blog_article.id'], name=op.f('fk_blog_article_version_article_id_blog_article'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['admin_users.id'], name=op.f('fk_blog_article_version_created_by_admin_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_article_version')),
    sa.UniqueConstraint('article_id', 'version_no', name='uq_blog_article_version_no')
    )
    op.create_table('blog_comment',
    sa.Column('article_id', sa.BigInteger(), nullable=False, comment='文章 ID'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='评论用户（业务用户）ID'),
    sa.Column('parent_id', sa.BigInteger(), nullable=True, comment='父评论 ID；NULL 表示顶层评论'),
    sa.Column('content', sa.Text(), nullable=False, comment='评论内容'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='状态；取值域待冻结'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Snowflake BIGINT 业务主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间 (UTC)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='逻辑删除时间 (UTC)，NULL 表示未删除'),
    sa.ForeignKeyConstraint(['article_id'], ['blog_article.id'], name=op.f('fk_blog_comment_article_id_blog_article'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_id'], ['blog_comment.id'], name=op.f('fk_blog_comment_parent_id_blog_comment'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['biz_user.id'], name=op.f('fk_blog_comment_user_id_biz_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_comment'))
    )
    op.create_index('ix_blog_comment_article_time', 'blog_comment', ['article_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_blog_comment_deleted_at'), 'blog_comment', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_blog_comment_parent_id'), 'blog_comment', ['parent_id'], unique=False)
    op.create_table('blog_favorite',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='业务用户 ID'),
    sa.Column('article_id', sa.BigInteger(), nullable=False, comment='文章 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Snowflake BIGINT 业务主键'),
    sa.ForeignKeyConstraint(['article_id'], ['blog_article.id'], name=op.f('fk_blog_favorite_article_id_blog_article'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['biz_user.id'], name=op.f('fk_blog_favorite_user_id_biz_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('user_id', 'article_id', 'id', name=op.f('pk_blog_favorite'))
    )
    op.create_table('blog_like',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='业务用户 ID'),
    sa.Column('article_id', sa.BigInteger(), nullable=False, comment='文章 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Snowflake BIGINT 业务主键'),
    sa.ForeignKeyConstraint(['article_id'], ['blog_article.id'], name=op.f('fk_blog_like_article_id_blog_article'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['biz_user.id'], name=op.f('fk_blog_like_user_id_biz_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('user_id', 'article_id', 'id', name=op.f('pk_blog_like'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_like')
    op.drop_table('blog_favorite')
    op.drop_index(op.f('ix_blog_comment_parent_id'), table_name='blog_comment')
    op.drop_index(op.f('ix_blog_comment_deleted_at'), table_name='blog_comment')
    op.drop_index('ix_blog_comment_article_time', table_name='blog_comment')
    op.drop_table('blog_comment')
    op.drop_table('blog_article_version')
    op.drop_table('blog_article_tag')
    op.drop_index('uq_blog_article_slug_active', table_name='blog_article', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_blog_article_deleted_at'), table_name='blog_article')
    op.drop_index('ix_blog_article_author_status', table_name='blog_article')
    op.drop_table('blog_article')
    op.drop_table('tool_version')
    op.drop_index('idx_tool_usage_tool_time', table_name='tool_usage_event')
    op.drop_table('tool_usage_event')
    op.drop_table('tool_recent_usage')
    op.drop_table('tool_access_policy')
    op.drop_table('blog_user_follow')
    op.drop_table('blog_author_application')
    op.drop_table('blog_author')
    op.drop_table('biz_user_verification')
    op.drop_table('biz_user_session')
    op.drop_table('biz_user_password_history')
    op.drop_table('biz_user_login_log')
    op.drop_table('biz_user_login_identity')
    op.drop_table('biz_user_achievement')
    op.drop_index('uq_tool_code_active', table_name='tool', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_tool_deleted_at'), table_name='tool')
    op.drop_table('tool')
    op.drop_table('biz_user_task')
    op.drop_index('idx_biz_point_tx_user_time', table_name='biz_user_point_transaction')
    op.drop_table('biz_user_point_transaction')
    op.drop_table('biz_user_level_history')
    op.drop_index('ix_biz_user_level_benefit_level', table_name='biz_user_level_benefit')
    op.drop_table('biz_user_level_benefit')
    op.drop_index('idx_biz_growth_tx_user_time', table_name='biz_user_growth_transaction')
    op.drop_table('biz_user_growth_transaction')
    op.drop_table('biz_user_growth_account')
    op.drop_table('biz_user_equipment')
    op.drop_table('biz_user_cosmetic')
    op.drop_index('uq_biz_user_username_active', table_name='biz_user', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_biz_user_deleted_at'), table_name='biz_user')
    op.drop_table('biz_user')
    op.drop_table('biz_achievement')
    op.drop_table('tool_usage_daily')
    op.drop_table('tool_popularity_daily')
    op.drop_table('tool_component_registry')
    op.drop_index('uq_tool_category_code_active', table_name='tool_category', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_tool_category_parent_id'), table_name='tool_category')
    op.drop_index(op.f('ix_tool_category_deleted_at'), table_name='tool_category')
    op.drop_table('tool_category')
    op.drop_table('blog_tag')
    op.drop_index('uq_blog_category_code_active', table_name='blog_category', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_blog_category_parent_id'), table_name='blog_category')
    op.drop_index(op.f('ix_blog_category_deleted_at'), table_name='blog_category')
    op.drop_table('blog_category')
    op.drop_table('biz_user_profile')
    op.drop_table('biz_user_point_account')
    op.drop_index('uq_biz_user_level_value_active', table_name='biz_user_level', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('uq_biz_user_level_code_active', table_name='biz_user_level', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_biz_user_level_deleted_at'), table_name='biz_user_level')
    op.drop_table('biz_user_level')
    op.drop_table('biz_task')
    op.drop_table('biz_point_rule')
    op.drop_table('biz_growth_rule')
    op.drop_index('ix_biz_growth_event_user_time', table_name='biz_growth_event')
    op.drop_index('ix_biz_growth_event_type_time', table_name='biz_growth_event')
    op.drop_table('biz_growth_event')
    op.drop_index('uq_biz_cosmetic_code_active', table_name='biz_cosmetic', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_biz_cosmetic_deleted_at'), table_name='biz_cosmetic')
    op.drop_table('biz_cosmetic')
    # ### end Alembic commands ###
