"""phase6 dd08 log tables

`06 §1` 的五类日志表 + `06 §2` 的 Audit append-only 强制。

表与保留期（`06 §1`）：

```text
access_logs       30 天   请求访问信息
security_logs    180 天   登录 / 锁定 / MFA / 密码 / Session / 安全事件
operation_logs   180 天   普通业务操作
audit_logs         2 年   高价值业务变更与管理员行为
application_logs  30 天   应用运行日志
```

append-only 为什么要在**数据库层**强制
------------------------------------
`10 §8` 要求 "Audit append-only"。只在 ORM 层"不提供 update 方法"是约定，
任何一次 `session.merge`、一条手写 SQL、一个临时脚本都能绕过。
审计的价值完全建立在"记录不可篡改"之上，因此这里加两道结构性防线：

1. `BEFORE UPDATE` 触发器 —— 无条件拒绝。事实记录不存在"更新"语义；
2. `DELETE` 守卫触发器 —— 只允许在**显式声明保留期清理意图**的事务里删除
   （会话级 GUC `vctn.retention = on`）。

第 2 条不是"方便实现"的让步：`06 §5` 要求必须提供归档 / 清理能力，
所以 DELETE 不能一律禁掉；把它收窄到"显式意图 + 可审计的操作"，
既满足保留期要求，又挡住"顺手清一下表"导致的证据灭失。
触发器同时覆盖五张表（五类日志都是事实记录）。

DD-08（日志分区）**仍处于未冻结**
-------------------------------
`16 §技术设计待冻结项` 中的 DD-08（PostgreSQL 声明式分区 / pg_partman /
归档到对象存储）尚未裁定，因此本次**不分区**，只建普通表 + 索引。
`06 §5` 的原文是"必须提供**后续**归档/清理能力"，本迁移满足该措辞；
分区与归档待日志量真正需要时再按 DD-08 的裁定实施 —— 届时是**纯增量**改动
（分区化不改列、不改查询，清理能力已由 `LogRetentionService` 提供）。

Revision ID: phase6_dd08
Revises: phase5_dd24
Create Date: 2026-09-25 08:45:55.427520

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'phase6_dd08'
down_revision: str | None = 'phase5_dd24'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: 五张日志表（与 `app/models/logs.py::LOG_MODELS` 一致）。
_LOG_TABLES: tuple[str, ...] = (
    "access_logs",
    "security_logs",
    "operation_logs",
    "audit_logs",
    "application_logs",
)

#: 保留期清理事务必须显式设置的会话级开关。
#:
#: 取值刻意用 `on` 而非 `true`：`current_setting(..., true)` 在**未设置**时
#: 返回 NULL，而 `IS DISTINCT FROM 'on'` 让 NULL 也走拒绝分支 ——
#: 这样"忘记设置"与"设置成别的值"都安全（fail-closed）。
_RETENTION_GUC = "vctn.retention"

_REJECT_UPDATE_FN = """
CREATE OR REPLACE FUNCTION vctn_reject_log_update() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'append-only 违规：% 不允许 UPDATE', TG_TABLE_NAME
        USING ERRCODE = 'restrict_violation';
END;
$$ LANGUAGE plpgsql;
"""

_GUARD_DELETE_FN = f"""
CREATE OR REPLACE FUNCTION vctn_guard_log_delete() RETURNS trigger AS $$
BEGIN
    IF current_setting('{_RETENTION_GUC}', true) IS DISTINCT FROM 'on' THEN
        RAISE EXCEPTION
            'append-only 违规：% 只允许经保留期清理删除（需 SET LOCAL {_RETENTION_GUC} = ''on''）',
            TG_TABLE_NAME
            USING ERRCODE = 'restrict_violation';
    END IF;
    RETURN OLD;
END;
$$ LANGUAGE plpgsql;
"""

_GUARD_TRUNCATE_FN = f"""
CREATE OR REPLACE FUNCTION vctn_guard_log_truncate() RETURNS trigger AS $$
BEGIN
    IF current_setting('{_RETENTION_GUC}', true) IS DISTINCT FROM 'on' THEN
        RAISE EXCEPTION
            'append-only 违规：% 不允许 TRUNCATE（需 SET LOCAL {_RETENTION_GUC} = ''on''）',
            TG_TABLE_NAME
            USING ERRCODE = 'restrict_violation';
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;
"""


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'access_logs',
        sa.Column('trace_id', sa.String(length=128), nullable=True),
        sa.Column('request_id', sa.String(length=128), nullable=True),
        sa.Column(
            'operator_id',
            sa.BigInteger(),
            nullable=True,
            comment='已认证时的用户 ID；未认证为 NULL',
        ),
        sa.Column('method', sa.String(length=16), nullable=False, comment='HTTP 方法'),
        sa.Column(
            'path', sa.String(length=512), nullable=False, comment='请求路径（不含 query）'
        ),
        sa.Column('status_code', sa.Integer(), nullable=False, comment='响应状态码'),
        sa.Column('duration_ms', sa.Integer(), nullable=False, comment='处理耗时（毫秒）'),
        sa.Column('ip', sa.String(length=64), nullable=True),
        sa.Column('user_agent', sa.String(length=512), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            'id',
            sa.BigInteger(),
            autoincrement=False,
            nullable=False,
            comment='Snowflake BIGINT 业务主键',
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_access_logs')),
    )
    op.create_index('ix_access_logs_created_at', 'access_logs', ['created_at'], unique=False)
    op.create_index(
        'ix_access_logs_path_created_at', 'access_logs', ['path', 'created_at'], unique=False
    )
    op.create_index(
        'ix_access_logs_status_code_created_at',
        'access_logs',
        ['status_code', 'created_at'],
        unique=False,
    )
    op.create_table(
        'application_logs',
        sa.Column('trace_id', sa.String(length=128), nullable=True),
        sa.Column('request_id', sa.String(length=128), nullable=True),
        sa.Column('level', sa.String(length=16), nullable=False, comment='日志级别'),
        sa.Column('logger', sa.String(length=255), nullable=False, comment='logger 名称'),
        sa.Column('message', sa.Text(), nullable=False, comment='日志正文（已脱敏）'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            'id',
            sa.BigInteger(),
            autoincrement=False,
            nullable=False,
            comment='Snowflake BIGINT 业务主键',
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_application_logs')),
    )
    op.create_index(
        'ix_application_logs_created_at', 'application_logs', ['created_at'], unique=False
    )
    op.create_index(
        'ix_application_logs_level_created_at',
        'application_logs',
        ['level', 'created_at'],
        unique=False,
    )
    op.create_index(
        'ix_application_logs_logger_created_at',
        'application_logs',
        ['logger', 'created_at'],
        unique=False,
    )
    op.create_table(
        'audit_logs',
        sa.Column(
            'trace_id',
            sa.String(length=128),
            nullable=True,
            comment='链路追踪 ID（Spec 06 §3）',
        ),
        sa.Column(
            'request_id',
            sa.String(length=128),
            nullable=True,
            comment='请求 ID（Spec 06 §3）',
        ),
        sa.Column(
            'operator_id',
            sa.BigInteger(),
            nullable=True,
            comment='操作者用户 ID；NULL = 操作者未知',
        ),
        sa.Column(
            'operator_username',
            sa.String(length=64),
            nullable=True,
            comment='操作者登录名（审计用）',
        ),
        sa.Column(
            'action', sa.String(length=64), nullable=False, comment='动作（AuditAction 取值）'
        ),
        sa.Column('resource_type', sa.String(length=64), nullable=False, comment='资源类型'),
        sa.Column(
            'resource_id',
            sa.BigInteger(),
            nullable=True,
            comment='资源 ID；NULL = 非单一资源（如全踢）',
        ),
        sa.Column(
            'before_data',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment='变更前数据（**已脱敏**，Spec 06 §4）',
        ),
        sa.Column(
            'after_data',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment='变更后数据（**已脱敏**，Spec 06 §4）',
        ),
        sa.Column(
            'result', sa.String(length=16), nullable=False, comment='结果 SUCCESS / FAILURE'
        ),
        sa.Column('error_code', sa.Integer(), nullable=True, comment='失败时的业务错误码'),
        sa.Column('ip', sa.String(length=64), nullable=True, comment='来源 IP'),
        sa.Column(
            'user_agent',
            sa.String(length=512),
            nullable=True,
            comment='User-Agent（非安全信号；超长时在写入前截断）',
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            nullable=False,
            comment='发生时间 (UTC)',
        ),
        sa.Column(
            'id',
            sa.BigInteger(),
            autoincrement=False,
            nullable=False,
            comment='Snowflake BIGINT 业务主键',
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs')),
    )
    op.create_index(
        'ix_audit_logs_action_created_at', 'audit_logs', ['action', 'created_at'], unique=False
    )
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index(
        'ix_audit_logs_operator_id_created_at',
        'audit_logs',
        ['operator_id', 'created_at'],
        unique=False,
    )
    op.create_index(
        'ix_audit_logs_resource_type_resource_id',
        'audit_logs',
        ['resource_type', 'resource_id'],
        unique=False,
    )
    op.create_index(
        'ix_audit_logs_trace_id_request_id',
        'audit_logs',
        ['trace_id', 'request_id'],
        unique=False,
    )
    op.create_table(
        'operation_logs',
        sa.Column('trace_id', sa.String(length=128), nullable=True),
        sa.Column('request_id', sa.String(length=128), nullable=True),
        sa.Column('operator_id', sa.BigInteger(), nullable=True),
        sa.Column('operator_username', sa.String(length=64), nullable=True),
        sa.Column('action', sa.String(length=64), nullable=False),
        sa.Column('resource_type', sa.String(length=64), nullable=False),
        sa.Column('resource_id', sa.BigInteger(), nullable=True),
        sa.Column('result', sa.String(length=16), nullable=False),
        sa.Column('error_code', sa.Integer(), nullable=True),
        sa.Column('ip', sa.String(length=64), nullable=True),
        sa.Column('user_agent', sa.String(length=512), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            'id',
            sa.BigInteger(),
            autoincrement=False,
            nullable=False,
            comment='Snowflake BIGINT 业务主键',
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_operation_logs')),
    )
    op.create_index(
        'ix_operation_logs_action_created_at',
        'operation_logs',
        ['action', 'created_at'],
        unique=False,
    )
    op.create_index(
        'ix_operation_logs_created_at', 'operation_logs', ['created_at'], unique=False
    )
    op.create_index(
        'ix_operation_logs_operator_id_created_at',
        'operation_logs',
        ['operator_id', 'created_at'],
        unique=False,
    )
    op.create_table(
        'security_logs',
        sa.Column('trace_id', sa.String(length=128), nullable=True),
        sa.Column('request_id', sa.String(length=128), nullable=True),
        sa.Column('operator_id', sa.BigInteger(), nullable=True),
        sa.Column('operator_username', sa.String(length=64), nullable=True),
        sa.Column(
            'event',
            sa.String(length=64),
            nullable=False,
            comment='安全事件名（同审计 action）',
        ),
        sa.Column('resource_type', sa.String(length=64), nullable=False),
        sa.Column('resource_id', sa.BigInteger(), nullable=True),
        sa.Column(
            'result', sa.String(length=16), nullable=False, comment='SUCCESS / FAILURE'
        ),
        sa.Column('error_code', sa.Integer(), nullable=True),
        sa.Column(
            'reason',
            sa.String(length=64),
            nullable=True,
            comment='拒绝/失败原因（供检索，如 LOCKED）',
        ),
        sa.Column('ip', sa.String(length=64), nullable=True),
        sa.Column('user_agent', sa.String(length=512), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            'id',
            sa.BigInteger(),
            autoincrement=False,
            nullable=False,
            comment='Snowflake BIGINT 业务主键',
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_security_logs')),
    )
    op.create_index(
        'ix_security_logs_created_at', 'security_logs', ['created_at'], unique=False
    )
    op.create_index(
        'ix_security_logs_event_created_at', 'security_logs', ['event', 'created_at'], unique=False
    )
    op.create_index(
        'ix_security_logs_operator_id_created_at',
        'security_logs',
        ['operator_id', 'created_at'],
        unique=False,
    )
    # ### end Alembic commands ###

    _install_append_only_guards()


def _install_append_only_guards() -> None:
    """为五张日志表安装 append-only 三道防线（拒绝 UPDATE / 受控 DELETE / 受控 TRUNCATE）。"""
    op.execute(_REJECT_UPDATE_FN)
    op.execute(_GUARD_DELETE_FN)
    op.execute(_GUARD_TRUNCATE_FN)
    for table in _LOG_TABLES:
        op.execute(
            f"""
            CREATE TRIGGER trg_{table}_no_update
            BEFORE UPDATE ON {table}
            FOR EACH ROW EXECUTE FUNCTION vctn_reject_log_update();
            """
        )
        op.execute(
            f"""
            CREATE TRIGGER trg_{table}_no_delete
            BEFORE DELETE ON {table}
            FOR EACH ROW EXECUTE FUNCTION vctn_guard_log_delete();
            """
        )
        op.execute(
            f"""
            CREATE TRIGGER trg_{table}_no_truncate
            BEFORE TRUNCATE ON {table}
            FOR EACH STATEMENT EXECUTE FUNCTION vctn_guard_log_truncate();
            """
        )


def downgrade() -> None:
    for table in _LOG_TABLES:
        op.execute(f"DROP TRIGGER IF EXISTS trg_{table}_no_truncate ON {table}")
        op.execute(f"DROP TRIGGER IF EXISTS trg_{table}_no_delete ON {table}")
        op.execute(f"DROP TRIGGER IF EXISTS trg_{table}_no_update ON {table}")
    op.execute("DROP FUNCTION IF EXISTS vctn_guard_log_truncate()")
    op.execute("DROP FUNCTION IF EXISTS vctn_guard_log_delete()")
    op.execute("DROP FUNCTION IF EXISTS vctn_reject_log_update()")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_security_logs_operator_id_created_at', table_name='security_logs')
    op.drop_index('ix_security_logs_event_created_at', table_name='security_logs')
    op.drop_index('ix_security_logs_created_at', table_name='security_logs')
    op.drop_table('security_logs')
    op.drop_index('ix_operation_logs_operator_id_created_at', table_name='operation_logs')
    op.drop_index('ix_operation_logs_created_at', table_name='operation_logs')
    op.drop_index('ix_operation_logs_action_created_at', table_name='operation_logs')
    op.drop_table('operation_logs')
    op.drop_index('ix_audit_logs_trace_id_request_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_resource_type_resource_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_operator_id_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action_created_at', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_application_logs_logger_created_at', table_name='application_logs')
    op.drop_index('ix_application_logs_level_created_at', table_name='application_logs')
    op.drop_index('ix_application_logs_created_at', table_name='application_logs')
    op.drop_table('application_logs')
    op.drop_index('ix_access_logs_status_code_created_at', table_name='access_logs')
    op.drop_index('ix_access_logs_path_created_at', table_name='access_logs')
    op.drop_index('ix_access_logs_created_at', table_name='access_logs')
    op.drop_table('access_logs')
    # ### end Alembic commands ###
