"""phase7 dict type item and system params

Phase 7 交付三张表：
  - `sys_dict_type` / `sys_dict_item`：Spec `05 §1`~`§3` 冻结的字典模型；
  - `sys_params`：Spec `05 §5` 的系统参数（表名未冻结，见下）。

表名 `sys_params` 为什么是 INTERIM
--------------------------------
`05 §5` 只规定"System Parameter 与 Dictionary 分离"以及"参数必须有类型、
默认值、状态、描述和审计"，**没有给出表名**；而同一份 Spec 的 §2 把字典表
命名为 `sys_dict_type` / `sys_dict_item`。取 `sys_params` 是对该命名惯例的
最小推导（同文档、同前缀、复数名词），登记为 INTERIM-7-01（见
`docs/DESIGN-DECISIONS.md` §14）。若人类冻结了另一个名字，改动面是
"一次 migration + 一处 `__tablename__`"。

三条 partial unique index 的含义（`07 §9` 的 soft-delete-aware unique）
--------------------------------------------------------------------
1. `uq_sys_dict_type_dict_code_active`：字典编码唯一，且**允许逻辑删除后
   用同一编码重建**（约束只覆盖 `deleted_at IS NULL` 的行）。
2. `uq_sys_dict_item_type_value_active`：`05 §3` 明文要求的
   "同一 dict type 下 item_value 软删除感知唯一"。
3. `uq_sys_dict_item_type_default_active`：每个字典**至多一个**默认项。
   Spec 未规定该项，但它把"自相矛盾的数据"（两个默认项无法回答取哪个）
   变成一次明确的写入失败；服务层同时会主动清理同字典其他行的 `is_default`，
   因此正常调用路径不会撞上它。登记为 INTERIM-7-03。

Seed：`mfa.required_default`
--------------------------
`docs/DESIGN-DECISIONS.md` §12.1 已裁定：MFA 的系统级默认值在 Phase 5
保持环境变量 `MFA_REQUIRED_DEFAULT`，**Phase 7 迁入系统参数表**。
因此本迁移写入该参数行。取值口径：

| 列 | 值 | 说明 |
|---|---|---|
| `param_key` | `mfa.required_default` | 与 `app/services/system_param.py` 的常量一致（有测试钉住） |
| `param_type` | `BOOL` | `05 §5` 的 "MFA default policy" 是布尔开关 |
| `param_value` | `NULL` | **未显式设置** → 生效值 = `default_value` |
| `default_value` | `false` | 与迁移前的环境变量默认值一致（**不改变既有行为**） |
| `status` | `ACTIVE` | 未停用 |

关于 Seed 的主键
--------------
Spec `07 §10` 要求 "Seed 数据的 ID 必须兼容 Snowflake BIGINT"。
该条要求的是**合法的 BIGINT 主键**，而不是"必须由 Snowflake 算法生成"——
若 Seed ID 每次生成都不同，migration 就不可重现、无法审查（`13 §3`）。
故此处取固定值 `700001`：生成器的最小可能输出为 `1 << 22 = 4194304`
（时间戳部分至少为 1，见 `app/core/snowflake.py` 的位分配），
因此该值**不可能**与运行期生成的 ID 碰撞。

Revision ID: phase7_dict
Revises: phase6_dd08
Create Date: 2026-09-25 09:46:26.629132

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'phase7_dict'
down_revision: str | None = 'phase6_dd08'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: `mfa.required_default` 参数行的固定主键（见模块说明）。
#:
#: 刻意写成字面量而不是从 `app.models` 导入：migration 必须能在
#: **当时的代码快照**下重放，导入会演进的业务常量会让历史迁移的行为
#: 随之后的提交改变。（常量与代码的一致性由测试钉住。）
_SEED_MFA_REQUIRED_DEFAULT_ID = 700001
_SEED_MFA_REQUIRED_DEFAULT_KEY = "mfa.required_default"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_dict_type',
    sa.Column('dict_code', sa.String(length=64), nullable=False, comment='字典编码；逻辑删除感知唯一（partial unique index），对外稳定标识，不可修改'),
    sa.Column('dict_name', sa.String(length=128), nullable=False, comment='字典名称'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='字典描述'),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', name='status', native_enum=False, create_constraint=True, length=16), nullable=False, comment='字典状态 ACTIVE / DISABLED；DISABLED 不参与公开查询'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Snowflake BIGINT 业务主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间 (UTC)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='逻辑删除时间 (UTC)，NULL 表示未删除'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_dict_type'))
    )
    op.create_index(op.f('ix_sys_dict_type_deleted_at'), 'sys_dict_type', ['deleted_at'], unique=False)
    op.create_index('uq_sys_dict_type_dict_code_active', 'sys_dict_type', ['dict_code'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('sys_params',
    sa.Column('param_key', sa.String(length=128), nullable=False, comment='参数键；逻辑删除感知唯一（partial unique index），对外稳定标识，不可修改'),
    sa.Column('param_name', sa.String(length=128), nullable=False, comment='参数名称（供后台展示）'),
    sa.Column('param_type', sa.Enum('STRING', 'INT', 'BOOL', name='param_type', native_enum=False, create_constraint=True, length=16), nullable=False, comment='类型 STRING / INT / BOOL（Spec 05 §5 要求参数必须有类型）'),
    sa.Column('param_value', sa.String(length=512), nullable=True, comment='当前值（字面量）；NULL 表示未显式设置，回落到 default_value'),
    sa.Column('default_value', sa.String(length=512), nullable=False, comment='默认值（字面量）；param_value 为 NULL 时生效'),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', name='status', native_enum=False, create_constraint=True, length=16), nullable=False, comment='参数状态 ACTIVE / DISABLED；DISABLED 时读取方 fail-closed'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='参数描述'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Snowflake BIGINT 业务主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间 (UTC)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='逻辑删除时间 (UTC)，NULL 表示未删除'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_params'))
    )
    op.create_index(op.f('ix_sys_params_deleted_at'), 'sys_params', ['deleted_at'], unique=False)
    op.create_index('uq_sys_params_param_key_active', 'sys_params', ['param_key'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('sys_dict_item',
    sa.Column('dict_type_id', sa.BigInteger(), nullable=False, comment='所属字典类型 ID'),
    sa.Column('item_label', sa.String(length=128), nullable=False, comment='展示文案'),
    sa.Column('item_value', sa.String(length=128), nullable=False, comment='取值；同字典内软删除感知唯一（partial unique index）'),
    sa.Column('item_code', sa.String(length=64), nullable=False, comment='编码（供代码引用的可读标识）'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序值（升序）；Spec 未规定取值范围，故不加 CHECK'),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', name='status', native_enum=False, create_constraint=True, length=16), nullable=False, comment='字典项状态 ACTIVE / DISABLED；DISABLED 不下发'),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='是否默认项；每个字典至多一个（partial unique index）'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='字典项描述'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Snowflake BIGINT 业务主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间 (UTC)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='逻辑删除时间 (UTC)，NULL 表示未删除'),
    sa.ForeignKeyConstraint(['dict_type_id'], ['sys_dict_type.id'], name=op.f('fk_sys_dict_item_dict_type_id_sys_dict_type'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_dict_item'))
    )
    op.create_index(op.f('ix_sys_dict_item_deleted_at'), 'sys_dict_item', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_sys_dict_item_dict_type_id'), 'sys_dict_item', ['dict_type_id'], unique=False)
    op.create_index('uq_sys_dict_item_type_default_active', 'sys_dict_item', ['dict_type_id'], unique=True, postgresql_where=sa.text('is_default AND deleted_at IS NULL'))
    op.create_index('uq_sys_dict_item_type_value_active', 'sys_dict_item', ['dict_type_id', 'item_value'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###

    # Seed：MFA 系统级默认值（DESIGN-DECISIONS §12.1 的既定安排）。
    #
    # `param_value = NULL` + `default_value = 'false'`：
    # 生效值为 false，与迁移前"环境变量缺省 false"完全一致 ——
    # 因此本迁移**不改变**任何既有登录行为（有端到端用例钉住这一点）。
    op.execute(
        sa.text(
            "INSERT INTO sys_params "
            "(id, param_key, param_name, param_type, param_value, default_value, "
            " status, description, created_at, updated_at) "
            "VALUES "
            "(:id, :key, :name, 'BOOL', NULL, 'false', 'ACTIVE', :description, "
            " now(), now())"
        ).bindparams(
            id=_SEED_MFA_REQUIRED_DEFAULT_ID,
            key=_SEED_MFA_REQUIRED_DEFAULT_KEY,
            name="MFA 系统级默认策略",
            description=(
                "策略链 user > role > system 的 system 级默认值（Spec 04 §7）。"
                "生效值 = param_value 非空则用它，否则用 default_value。"
            ),
        )
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_sys_dict_item_type_value_active', table_name='sys_dict_item', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('uq_sys_dict_item_type_default_active', table_name='sys_dict_item', postgresql_where=sa.text('is_default AND deleted_at IS NULL'))
    op.drop_index(op.f('ix_sys_dict_item_dict_type_id'), table_name='sys_dict_item')
    op.drop_index(op.f('ix_sys_dict_item_deleted_at'), table_name='sys_dict_item')
    op.drop_table('sys_dict_item')
    # `sys_params` 被删除时其中的 Seed 行随之消失，无需额外 DELETE。
    op.drop_index('uq_sys_params_param_key_active', table_name='sys_params', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_sys_params_deleted_at'), table_name='sys_params')
    op.drop_table('sys_params')
    op.drop_index('uq_sys_dict_type_dict_code_active', table_name='sys_dict_type', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_sys_dict_type_deleted_at'), table_name='sys_dict_type')
    op.drop_table('sys_dict_type')
    # ### end Alembic commands ###
