"""phase 2 organization user role models

Revision ID: fdbaf573ca04
Revises: 6bdb6b4ec5df
Create Date: 2026-09-23 22:31:38.237055

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fdbaf573ca04'
down_revision: str | None = '6bdb6b4ec5df'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('parent_id', sa.BigInteger(), nullable=True, comment='父部门 ID；NULL 表示根部门'),
    sa.Column('department_code', sa.String(length=64), nullable=False, comment='部门编码；逻辑删除感知唯一（partial unique index）'),
    sa.Column('department_name', sa.String(length=128), nullable=False, comment='部门名称'),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', name='status', native_enum=False, create_constraint=True, length=16), nullable=False, comment='部门状态 ACTIVE / DISABLED'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Snowflake BIGINT 业务主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间 (UTC)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='逻辑删除时间 (UTC)，NULL 表示未删除'),
    sa.CheckConstraint('parent_id IS NULL OR parent_id <> id', name=op.f('ck_departments_parent_not_self')),
    sa.ForeignKeyConstraint(['parent_id'], ['departments.id'], name=op.f('fk_departments_parent_id_departments'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments'))
    )
    op.create_index(op.f('ix_departments_deleted_at'), 'departments', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_departments_parent_id'), 'departments', ['parent_id'], unique=False)
    op.create_index('uq_departments_department_code_active', 'departments', ['department_code'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('roles',
    sa.Column('role_code', sa.String(length=64), nullable=False, comment='角色编码；逻辑删除感知唯一'),
    sa.Column('role_name', sa.String(length=128), nullable=False, comment='角色名称'),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', name='status', native_enum=False, create_constraint=True, length=16), nullable=False, comment='角色状态 ACTIVE / DISABLED'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='角色描述'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Snowflake BIGINT 业务主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间 (UTC)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='逻辑删除时间 (UTC)，NULL 表示未删除'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    op.create_index(op.f('ix_roles_deleted_at'), 'roles', ['deleted_at'], unique=False)
    op.create_index('uq_roles_role_code_active', 'roles', ['role_code'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('admin_users',
    sa.Column('username', sa.String(length=64), nullable=False, comment='登录名；逻辑删除感知唯一（partial unique index）'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='argon2id 哈希；绝不返回 API、绝不写入日志'),
    sa.Column('display_name', sa.String(length=128), nullable=False, comment='显示名称'),
    sa.Column('phone', sa.String(length=32), nullable=True, comment='手机号；日志与响应必须脱敏'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='邮箱；日志与响应必须脱敏'),
    sa.Column('department_id', sa.BigInteger(), nullable=True, comment='所属部门；数据范围计算的关键列'),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', 'LOCKED', name='status', native_enum=False, create_constraint=True, length=16), nullable=False, comment='用户状态 ACTIVE / DISABLED / LOCKED；逻辑删除由 deleted_at 表达'),
    sa.Column('failed_login_count', sa.Integer(), nullable=False, comment='连续登录失败次数；达到 5 次触发锁定'),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True, comment='锁定截止时间 (UTC)；NULL 表示未锁定'),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True, comment='上次改密时间 (UTC)；用于 90 天过期判断与历史校验'),
    sa.Column('must_change_password', sa.Boolean(), nullable=False, comment='管理员重置密码后置 True，首次登录必须改密'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Snowflake BIGINT 业务主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间 (UTC)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='逻辑删除时间 (UTC)，NULL 表示未删除'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_admin_users_department_id_departments'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_users'))
    )
    op.create_index(op.f('ix_admin_users_deleted_at'), 'admin_users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_admin_users_department_id'), 'admin_users', ['department_id'], unique=False)
    op.create_index('uq_admin_users_username_active', 'admin_users', ['username'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('admin_user_password_histories',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户 ID'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='历史密码的 argon2id 哈希；绝不保存明文'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='写入时间 (UTC)'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Snowflake BIGINT 业务主键'),
    sa.ForeignKeyConstraint(['user_id'], ['admin_users.id'], name=op.f('fk_admin_user_password_histories_user_id_admin_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_user_password_histories'))
    )
    op.create_index('ix_admin_user_password_histories_user_id_created_at', 'admin_user_password_histories', ['user_id', 'created_at'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户 ID'),
    sa.Column('role_id', sa.BigInteger(), nullable=False, comment='角色 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='授予时间 (UTC)'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['admin_users.id'], name=op.f('fk_user_roles_user_id_admin_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index('ix_admin_user_password_histories_user_id_created_at', table_name='admin_user_password_histories')
    op.drop_table('admin_user_password_histories')
    op.drop_index('uq_admin_users_username_active', table_name='admin_users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_admin_users_department_id'), table_name='admin_users')
    op.drop_index(op.f('ix_admin_users_deleted_at'), table_name='admin_users')
    op.drop_table('admin_users')
    op.drop_index('uq_roles_role_code_active', table_name='roles', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_roles_deleted_at'), table_name='roles')
    op.drop_table('roles')
    op.drop_index('uq_departments_department_code_active', table_name='departments', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_departments_parent_id'), table_name='departments')
    op.drop_index(op.f('ix_departments_deleted_at'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
