"""phase 3 role data scope and custom scope departments

Revision ID: phase3_dd07
Revises: fdbaf573ca04
Create Date: 2026-09-24 10:53:53.702649

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'phase3_dd07'
down_revision: str | None = 'fdbaf573ca04'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_custom_scope_departments',
    sa.Column('role_id', sa.BigInteger(), nullable=False, comment='角色 ID'),
    sa.Column('department_id', sa.BigInteger(), nullable=False, comment='CUSTOM 范围内可见的部门 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='写入时间 (UTC)'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_role_custom_scope_departments_department_id_departments'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_custom_scope_departments_role_id_roles'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('role_id', 'department_id', name=op.f('pk_role_custom_scope_departments'))
    )
    op.create_index(op.f('ix_role_custom_scope_departments_department_id'), 'role_custom_scope_departments', ['department_id'], unique=False)
    op.add_column('roles', sa.Column('data_scope', sa.Enum('ALL', 'DEPARTMENT', 'DEPARTMENT_CHILDREN', 'SELF', 'CUSTOM', name='data_scope', native_enum=False, create_constraint=True, length=32), server_default='DEPARTMENT_CHILDREN', nullable=False, comment='角色数据范围（Spec 03 §10）；默认 DEPARTMENT_CHILDREN（部门管理员默认值）'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'data_scope')
    op.drop_index(op.f('ix_role_custom_scope_departments_department_id'), table_name='role_custom_scope_departments')
    op.drop_table('role_custom_scope_departments')
    # ### end Alembic commands ###
