"""phase 4 sessions

Revision ID: phase4_dd02
Revises: phase3_dd20
Create Date: 2026-09-24 21:31:09.301150

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'phase4_dd02'
down_revision: str | None = 'phase3_dd20'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='会话所属用户 ID'),
    sa.Column('access_token_hash', sa.String(length=64), nullable=False, comment='当前 Access Token 的 SHA-256；绝不保存明文（Spec 10 §4）'),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False, comment='当前 Refresh Token 的 SHA-256；绝不保存明文（Spec 04 §3）'),
    sa.Column('login_at', sa.DateTime(timezone=True), nullable=False, comment='登录时间 (UTC)'),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=False, comment='最近活动时间 (UTC)；写放大受 SESSION_ACTIVITY_WRITE_INTERVAL 抑制'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='当前 Access Token 过期时间 (UTC)；轮换时前移，不延长会话总寿命'),
    sa.Column('refresh_expires_at', sa.DateTime(timezone=True), nullable=False, comment='Refresh Token 过期时间 (UTC)；登录时确定，轮换**不**延长（DD-02 P2 固定）'),
    sa.Column('ip', sa.String(length=64), nullable=True, comment='登录来源 IP；可空（代理/内网场景可能取不到）'),
    sa.Column('user_agent', sa.String(length=512), nullable=True, comment='原始 User-Agent，仅用于展示与取证'),
    sa.Column('device', sa.String(length=128), nullable=True, comment='设备粗分类（启发式，**非安全依据**；见 app.core.security.device）'),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True, comment='撤销时间 (UTC)；NULL 表示仍有效。改此列即**立即**生效（Spec 10 §7）'),
    sa.Column('revoke_reason', sa.Enum('LOGOUT', 'ADMIN_REVOKE', 'REVOKE_ALL', 'TOKEN_REUSE_DETECTED', name='revoke_reason', native_enum=False, create_constraint=True, length=32), nullable=True, comment='撤销原因；与 revoked_at 同生共死（CHECK 保证）'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Snowflake BIGINT 业务主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间 (UTC)'),
    sa.CheckConstraint('(revoked_at IS NULL) = (revoke_reason IS NULL)', name=op.f('ck_sessions_revocation_fields_consistent')),
    sa.CheckConstraint('expires_at > login_at', name=op.f('ck_sessions_access_expires_after_login')),
    sa.CheckConstraint('refresh_expires_at >= expires_at', name=op.f('ck_sessions_refresh_expires_not_before_access')),
    sa.ForeignKeyConstraint(['user_id'], ['admin_users.id'], name=op.f('fk_sessions_user_id_admin_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_index('uq_sessions_access_token_hash', 'sessions', ['access_token_hash'], unique=True)
    op.create_index('uq_sessions_refresh_token_hash', 'sessions', ['refresh_token_hash'], unique=True)
    op.create_table('session_refresh_token_history',
    sa.Column('session_id', sa.BigInteger(), nullable=False, comment='该令牌所属会话 ID'),
    sa.Column('token_hash', sa.String(length=64), nullable=False, comment='已退役 Refresh Token 的 SHA-256；绝不保存明文'),
    sa.Column('reason', sa.Enum('ROTATED', 'SESSION_REVOKED', name='reason', native_enum=False, create_constraint=True, length=32), nullable=False, comment='退役原因：ROTATED（盗用信号）/ SESSION_REVOKED（会话已撤销）'),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=False, comment='退役时间 (UTC)'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Snowflake BIGINT 业务主键'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_session_refresh_token_history_session_id_sessions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_refresh_token_history'))
    )
    op.create_index(op.f('ix_session_refresh_token_history_session_id'), 'session_refresh_token_history', ['session_id'], unique=False)
    op.create_index('uq_session_refresh_token_history_token_hash', 'session_refresh_token_history', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_session_refresh_token_history_token_hash', table_name='session_refresh_token_history')
    op.drop_index(op.f('ix_session_refresh_token_history_session_id'), table_name='session_refresh_token_history')
    op.drop_table('session_refresh_token_history')
    op.drop_index('uq_sessions_refresh_token_hash', table_name='sessions')
    op.drop_index('uq_sessions_access_token_hash', table_name='sessions')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###
