/**
 * V3.1 四新增域结构层实体的列元数据（VCTN §33，自动生成）。
 *
 * 供 `views/crud/CrudResourcePanel.vue` 渲染通用 CRUD 表格与表单。
 *
 * ⚠️ 本文件由 `scripts/gen_v31_crud.py` 覆盖生成，不要手改：
 * 手工修改会在下次重新生成时静默丢失。要改列，改模型或改生成器。
 */

export type V31ColumnType =
  | 'string' | 'number' | 'boolean' | 'enum'
  | 'date' | 'datetime' | 'json' | 'fk'

export interface V31ColumnMeta {
  key: string
  label: string
  type: V31ColumnType
  required: boolean
  filterable: boolean
  formable: boolean
  maxLength?: number
  enumType?: string
}

export interface V31ResourceMeta {
  resourceType: string
  kebab: string
  title: string
  columns: V31ColumnMeta[]
}

export const V31_META: Record<string, V31ResourceMeta> = {
  'biz_user': {
    resourceType: 'biz_user',
    kebab: 'biz-user',
    title: 'BizUser',
    columns: [
      {
        key: 'username',
        label: 'Username',
        type: 'string',
        required: true,
        filterable: false,
        formable: true,
        maxLength: 64,
      },
      {
        key: 'status',
        label: 'Status',
        type: 'string',
        required: false,
        filterable: true,
        formable: true,
        maxLength: 32,
      },
      {
        key: 'user_level_id',
        label: 'User Level Id',
        type: 'fk',
        required: false,
        filterable: true,
        formable: true,
      },
      {
        key: 'must_change_password',
        label: 'Must Change Password',
        type: 'boolean',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'password_changed_at',
        label: 'Password Changed At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'password_expires_at',
        label: 'Password Expires At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'last_login_at',
        label: 'Last Login At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'last_login_ip',
        label: 'Last Login Ip',
        type: 'string',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'id',
        label: 'Id',
        type: 'number',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'created_at',
        label: 'Created At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'updated_at',
        label: 'Updated At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'deleted_at',
        label: 'Deleted At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
    ],
  },
  'biz_user_level': {
    resourceType: 'biz_user_level',
    kebab: 'biz-user-level',
    title: 'BizUserLevel',
    columns: [
      {
        key: 'code',
        label: 'Code',
        type: 'string',
        required: true,
        filterable: true,
        formable: true,
        maxLength: 64,
      },
      {
        key: 'name',
        label: 'Name',
        type: 'string',
        required: true,
        filterable: false,
        formable: true,
        maxLength: 128,
      },
      {
        key: 'level_value',
        label: 'Level Value',
        type: 'number',
        required: true,
        filterable: false,
        formable: true,
      },
      {
        key: 'required_growth_points',
        label: 'Required Growth Points',
        type: 'number',
        required: true,
        filterable: false,
        formable: true,
      },
      {
        key: 'icon_url',
        label: 'Icon Url',
        type: 'string',
        required: false,
        filterable: false,
        formable: true,
        maxLength: 512,
      },
      {
        key: 'status',
        label: 'Status',
        type: 'string',
        required: false,
        filterable: true,
        formable: true,
        maxLength: 32,
      },
      {
        key: 'sort_order',
        label: 'Sort Order',
        type: 'number',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'description',
        label: 'Description',
        type: 'string',
        required: false,
        filterable: false,
        formable: true,
        maxLength: 500,
      },
      {
        key: 'id',
        label: 'Id',
        type: 'number',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'created_at',
        label: 'Created At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'updated_at',
        label: 'Updated At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'deleted_at',
        label: 'Deleted At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
    ],
  },
  'biz_user_login_identity': {
    resourceType: 'biz_user_login_identity',
    kebab: 'biz-user-login-identity',
    title: 'BizUserLoginIdentity',
    columns: [
      {
        key: 'user_id',
        label: 'User Id',
        type: 'fk',
        required: true,
        filterable: true,
        formable: true,
      },
      {
        key: 'identity_type',
        label: 'Identity Type',
        type: 'enum',
        required: true,
        filterable: false,
        formable: true,
        maxLength: 16,
        enumType: 'BizUserLoginIdentityType',
      },
      {
        key: 'normalized_value',
        label: 'Normalized Value',
        type: 'string',
        required: true,
        filterable: false,
        formable: true,
        maxLength: 255,
      },
      {
        key: 'verified',
        label: 'Verified',
        type: 'boolean',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'is_primary',
        label: 'Is Primary',
        type: 'boolean',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'id',
        label: 'Id',
        type: 'number',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'created_at',
        label: 'Created At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'updated_at',
        label: 'Updated At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
    ],
  },
  'biz_user_login_log': {
    resourceType: 'biz_user_login_log',
    kebab: 'biz-user-login-log',
    title: 'BizUserLoginLog',
    columns: [
      {
        key: 'user_id',
        label: 'User Id',
        type: 'fk',
        required: true,
        filterable: true,
        formable: true,
      },
      {
        key: 'success',
        label: 'Success',
        type: 'boolean',
        required: true,
        filterable: false,
        formable: true,
      },
      {
        key: 'fail_reason',
        label: 'Fail Reason',
        type: 'string',
        required: false,
        filterable: false,
        formable: true,
        maxLength: 255,
      },
      {
        key: 'ip',
        label: 'Ip',
        type: 'string',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'user_agent',
        label: 'User Agent',
        type: 'string',
        required: false,
        filterable: false,
        formable: true,
        maxLength: 1000,
      },
      {
        key: 'created_at',
        label: 'Created At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'id',
        label: 'Id',
        type: 'number',
        required: false,
        filterable: false,
        formable: false,
      },
    ],
  },
  'biz_user_password_history': {
    resourceType: 'biz_user_password_history',
    kebab: 'biz-user-password-history',
    title: 'BizUserPasswordHistory',
    columns: [
      {
        key: 'user_id',
        label: 'User Id',
        type: 'fk',
        required: true,
        filterable: true,
        formable: true,
      },
      {
        key: 'id',
        label: 'Id',
        type: 'number',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'created_at',
        label: 'Created At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'updated_at',
        label: 'Updated At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
    ],
  },
  'biz_user_profile': {
    resourceType: 'biz_user_profile',
    kebab: 'biz-user-profile',
    title: 'BizUserProfile',
    columns: [
      {
        key: 'user_id',
        label: 'User Id',
        type: 'number',
        required: true,
        filterable: false,
        formable: true,
      },
      {
        key: 'nickname',
        label: 'Nickname',
        type: 'string',
        required: false,
        filterable: false,
        formable: true,
        maxLength: 128,
      },
      {
        key: 'avatar_url',
        label: 'Avatar Url',
        type: 'string',
        required: false,
        filterable: false,
        formable: true,
        maxLength: 512,
      },
      {
        key: 'bio',
        label: 'Bio',
        type: 'string',
        required: false,
        filterable: false,
        formable: true,
        maxLength: 1000,
      },
      {
        key: 'gender',
        label: 'Gender',
        type: 'string',
        required: false,
        filterable: false,
        formable: true,
        maxLength: 32,
      },
      {
        key: 'birthday',
        label: 'Birthday',
        type: 'date',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'id',
        label: 'Id',
        type: 'number',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'created_at',
        label: 'Created At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'updated_at',
        label: 'Updated At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
    ],
  },
  'biz_user_session': {
    resourceType: 'biz_user_session',
    kebab: 'biz-user-session',
    title: 'BizUserSession',
    columns: [
      {
        key: 'user_id',
        label: 'User Id',
        type: 'fk',
        required: true,
        filterable: true,
        formable: true,
      },
      {
        key: 'session_id',
        label: 'Session Id',
        type: 'string',
        required: true,
        filterable: false,
        formable: true,
        maxLength: 128,
      },
      {
        key: 'ip',
        label: 'Ip',
        type: 'string',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'user_agent',
        label: 'User Agent',
        type: 'string',
        required: false,
        filterable: false,
        formable: true,
        maxLength: 1000,
      },
      {
        key: 'login_at',
        label: 'Login At',
        type: 'datetime',
        required: true,
        filterable: false,
        formable: true,
      },
      {
        key: 'last_seen_at',
        label: 'Last Seen At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'expires_at',
        label: 'Expires At',
        type: 'datetime',
        required: true,
        filterable: false,
        formable: true,
      },
      {
        key: 'revoked_at',
        label: 'Revoked At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'revoke_reason',
        label: 'Revoke Reason',
        type: 'string',
        required: false,
        filterable: false,
        formable: true,
        maxLength: 255,
      },
      {
        key: 'id',
        label: 'Id',
        type: 'number',
        required: false,
        filterable: false,
        formable: false,
      },
    ],
  },
  'biz_user_verification': {
    resourceType: 'biz_user_verification',
    kebab: 'biz-user-verification',
    title: 'BizUserVerification',
    columns: [
      {
        key: 'user_id',
        label: 'User Id',
        type: 'fk',
        required: true,
        filterable: true,
        formable: true,
      },
      {
        key: 'identity_type',
        label: 'Identity Type',
        type: 'string',
        required: true,
        filterable: false,
        formable: true,
        maxLength: 32,
      },
      {
        key: 'token_hash',
        label: 'Token Hash',
        type: 'string',
        required: true,
        filterable: false,
        formable: true,
        maxLength: 255,
      },
      {
        key: 'expires_at',
        label: 'Expires At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'verified',
        label: 'Verified',
        type: 'boolean',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'created_at',
        label: 'Created At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'id',
        label: 'Id',
        type: 'number',
        required: false,
        filterable: false,
        formable: false,
      },
    ],
  },
  'biz_achievement': {
    resourceType: 'biz_achievement',
    kebab: 'biz-achievement',
    title: 'BizAchievement',
    columns: [
      {
        key: 'code',
        label: 'Code',
        type: 'string',
        required: true,
        filterable: true,
        formable: true,
        maxLength: 64,
      },
      {
        key: 'name',
        label: 'Name',
        type: 'string',
        required: true,
        filterable: false,
        formable: true,
        maxLength: 128,
      },
      {
        key: 'icon_url',
        label: 'Icon Url',
        type: 'string',
        required: false,
        filterable: false,
        formable: true,
        maxLength: 512,
      },
      {
        key: 'achievement_type',
        label: 'Achievement Type',
        type: 'string',
        required: true,
        filterable: false,
        formable: true,
        maxLength: 64,
      },
      {
        key: 'target_value',
        label: 'Target Value',
        type: 'number',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'reward_growth_points',
        label: 'Reward Growth Points',
        type: 'number',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'reward_points',
        label: 'Reward Points',
        type: 'number',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'reward_cosmetic_id',
        label: 'Reward Cosmetic Id',
        type: 'fk',
        required: false,
        filterable: true,
        formable: true,
      },
      {
        key: 'status',
        label: 'Status',
        type: 'string',
        required: false,
        filterable: true,
        formable: true,
        maxLength: 32,
      },
      {
        key: 'id',
        label: 'Id',
        type: 'number',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'created_at',
        label: 'Created At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'updated_at',
        label: 'Updated At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
    ],
  },
  'biz_cosmetic': {
    resourceType: 'biz_cosmetic',
    kebab: 'biz-cosmetic',
    title: 'BizCosmetic',
    columns: [
      {
        key: 'code',
        label: 'Code',
        type: 'string',
        required: true,
        filterable: true,
        formable: true,
        maxLength: 128,
      },
      {
        key: 'name',
        label: 'Name',
        type: 'string',
        required: true,
        filterable: false,
        formable: true,
        maxLength: 128,
      },
      {
        key: 'cosmetic_type',
        label: 'Cosmetic Type',
        type: 'enum',
        required: true,
        filterable: false,
        formable: true,
        maxLength: 16,
        enumType: 'CosmeticType',
      },
      {
        key: 'image_url',
        label: 'Image Url',
        type: 'string',
        required: false,
        filterable: false,
        formable: true,
        maxLength: 512,
      },
      {
        key: 'animation_url',
        label: 'Animation Url',
        type: 'string',
        required: false,
        filterable: false,
        formable: true,
        maxLength: 512,
      },
      {
        key: 'rarity',
        label: 'Rarity',
        type: 'string',
        required: false,
        filterable: false,
        formable: true,
        maxLength: 32,
      },
      {
        key: 'status',
        label: 'Status',
        type: 'string',
        required: false,
        filterable: true,
        formable: true,
        maxLength: 32,
      },
      {
        key: 'description',
        label: 'Description',
        type: 'string',
        required: false,
        filterable: false,
        formable: true,
        maxLength: 500,
      },
      {
        key: 'id',
        label: 'Id',
        type: 'number',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'created_at',
        label: 'Created At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'updated_at',
        label: 'Updated At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'deleted_at',
        label: 'Deleted At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
    ],
  },
  'biz_growth_event': {
    resourceType: 'biz_growth_event',
    kebab: 'biz-growth-event',
    title: 'BizGrowthEvent',
    columns: [
      {
        key: 'event_id',
        label: 'Event Id',
        type: 'string',
        required: true,
        filterable: false,
        formable: true,
        maxLength: 128,
      },
      {
        key: 'user_id',
        label: 'User Id',
        type: 'number',
        required: true,
        filterable: false,
        formable: true,
      },
      {
        key: 'source_type',
        label: 'Source Type',
        type: 'string',
        required: true,
        filterable: false,
        formable: true,
        maxLength: 64,
      },
      {
        key: 'source_id',
        label: 'Source Id',
        type: 'string',
        required: false,
        filterable: false,
        formable: true,
        maxLength: 128,
      },
      {
        key: 'event_type',
        label: 'Event Type',
        type: 'string',
        required: true,
        filterable: false,
        formable: true,
        maxLength: 128,
      },
      {
        key: 'idempotency_key',
        label: 'Idempotency Key',
        type: 'string',
        required: true,
        filterable: false,
        formable: true,
        maxLength: 255,
      },
      {
        key: 'event_data',
        label: 'Event Data',
        type: 'json',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'processed',
        label: 'Processed',
        type: 'boolean',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'created_at',
        label: 'Created At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'processed_at',
        label: 'Processed At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'id',
        label: 'Id',
        type: 'number',
        required: false,
        filterable: false,
        formable: false,
      },
    ],
  },
  'biz_growth_rule': {
    resourceType: 'biz_growth_rule',
    kebab: 'biz-growth-rule',
    title: 'BizGrowthRule',
    columns: [
      {
        key: 'code',
        label: 'Code',
        type: 'string',
        required: true,
        filterable: true,
        formable: true,
        maxLength: 64,
      },
      {
        key: 'name',
        label: 'Name',
        type: 'string',
        required: true,
        filterable: false,
        formable: true,
        maxLength: 128,
      },
      {
        key: 'source_type',
        label: 'Source Type',
        type: 'string',
        required: true,
        filterable: false,
        formable: true,
        maxLength: 64,
      },
      {
        key: 'event_type',
        label: 'Event Type',
        type: 'string',
        required: true,
        filterable: false,
        formable: true,
        maxLength: 128,
      },
      {
        key: 'reward_points',
        label: 'Reward Points',
        type: 'number',
        required: true,
        filterable: false,
        formable: true,
      },
      {
        key: 'daily_limit',
        label: 'Daily Limit',
        type: 'number',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'weekly_limit',
        label: 'Weekly Limit',
        type: 'number',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'monthly_limit',
        label: 'Monthly Limit',
        type: 'number',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'cooldown_seconds',
        label: 'Cooldown Seconds',
        type: 'number',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'requires_success',
        label: 'Requires Success',
        type: 'boolean',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'status',
        label: 'Status',
        type: 'string',
        required: false,
        filterable: true,
        formable: true,
        maxLength: 32,
      },
      {
        key: 'effective_from',
        label: 'Effective From',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'effective_to',
        label: 'Effective To',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'description',
        label: 'Description',
        type: 'string',
        required: false,
        filterable: false,
        formable: true,
        maxLength: 500,
      },
      {
        key: 'id',
        label: 'Id',
        type: 'number',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'created_at',
        label: 'Created At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'updated_at',
        label: 'Updated At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
    ],
  },
  'biz_point_rule': {
    resourceType: 'biz_point_rule',
    kebab: 'biz-point-rule',
    title: 'BizPointRule',
    columns: [
      {
        key: 'code',
        label: 'Code',
        type: 'string',
        required: true,
        filterable: true,
        formable: true,
        maxLength: 64,
      },
      {
        key: 'name',
        label: 'Name',
        type: 'string',
        required: true,
        filterable: false,
        formable: true,
        maxLength: 128,
      },
      {
        key: 'source_type',
        label: 'Source Type',
        type: 'string',
        required: true,
        filterable: false,
        formable: true,
        maxLength: 64,
      },
      {
        key: 'event_type',
        label: 'Event Type',
        type: 'string',
        required: true,
        filterable: false,
        formable: true,
        maxLength: 128,
      },
      {
        key: 'reward_points',
        label: 'Reward Points',
        type: 'number',
        required: true,
        filterable: false,
        formable: true,
      },
      {
        key: 'daily_limit',
        label: 'Daily Limit',
        type: 'number',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'weekly_limit',
        label: 'Weekly Limit',
        type: 'number',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'monthly_limit',
        label: 'Monthly Limit',
        type: 'number',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'cooldown_seconds',
        label: 'Cooldown Seconds',
        type: 'number',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'requires_success',
        label: 'Requires Success',
        type: 'boolean',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'status',
        label: 'Status',
        type: 'string',
        required: false,
        filterable: true,
        formable: true,
        maxLength: 32,
      },
      {
        key: 'effective_from',
        label: 'Effective From',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'effective_to',
        label: 'Effective To',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'description',
        label: 'Description',
        type: 'string',
        required: false,
        filterable: false,
        formable: true,
        maxLength: 500,
      },
      {
        key: 'id',
        label: 'Id',
        type: 'number',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'created_at',
        label: 'Created At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'updated_at',
        label: 'Updated At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
    ],
  },
  'biz_task': {
    resourceType: 'biz_task',
    kebab: 'biz-task',
    title: 'BizTask',
    columns: [
      {
        key: 'code',
        label: 'Code',
        type: 'string',
        required: true,
        filterable: true,
        formable: true,
        maxLength: 64,
      },
      {
        key: 'name',
        label: 'Name',
        type: 'string',
        required: true,
        filterable: false,
        formable: true,
        maxLength: 128,
      },
      {
        key: 'task_type',
        label: 'Task Type',
        type: 'string',
        required: true,
        filterable: false,
        formable: true,
        maxLength: 64,
      },
      {
        key: 'target_value',
        label: 'Target Value',
        type: 'number',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'reward_growth_points',
        label: 'Reward Growth Points',
        type: 'number',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'reward_points',
        label: 'Reward Points',
        type: 'number',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'repeat_type',
        label: 'Repeat Type',
        type: 'string',
        required: false,
        filterable: false,
        formable: true,
        maxLength: 32,
      },
      {
        key: 'status',
        label: 'Status',
        type: 'string',
        required: false,
        filterable: true,
        formable: true,
        maxLength: 32,
      },
      {
        key: 'effective_from',
        label: 'Effective From',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'effective_to',
        label: 'Effective To',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'id',
        label: 'Id',
        type: 'number',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'created_at',
        label: 'Created At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'updated_at',
        label: 'Updated At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
    ],
  },
  'biz_user_achievement': {
    resourceType: 'biz_user_achievement',
    kebab: 'biz-user-achievement',
    title: 'BizUserAchievement',
    columns: [
      {
        key: 'user_id',
        label: 'User Id',
        type: 'number',
        required: true,
        filterable: false,
        formable: true,
      },
      {
        key: 'achievement_id',
        label: 'Achievement Id',
        type: 'fk',
        required: true,
        filterable: true,
        formable: true,
      },
      {
        key: 'progress',
        label: 'Progress',
        type: 'number',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'completed_at',
        label: 'Completed At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'created_at',
        label: 'Created At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'id',
        label: 'Id',
        type: 'number',
        required: false,
        filterable: false,
        formable: false,
      },
    ],
  },
  'biz_user_cosmetic': {
    resourceType: 'biz_user_cosmetic',
    kebab: 'biz-user-cosmetic',
    title: 'BizUserCosmetic',
    columns: [
      {
        key: 'user_id',
        label: 'User Id',
        type: 'number',
        required: true,
        filterable: false,
        formable: true,
      },
      {
        key: 'cosmetic_id',
        label: 'Cosmetic Id',
        type: 'fk',
        required: true,
        filterable: true,
        formable: true,
      },
      {
        key: 'source_type',
        label: 'Source Type',
        type: 'string',
        required: true,
        filterable: false,
        formable: true,
        maxLength: 64,
      },
      {
        key: 'source_id',
        label: 'Source Id',
        type: 'string',
        required: false,
        filterable: false,
        formable: true,
        maxLength: 128,
      },
      {
        key: 'acquired_at',
        label: 'Acquired At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'id',
        label: 'Id',
        type: 'number',
        required: false,
        filterable: false,
        formable: false,
      },
    ],
  },
  'biz_user_equipment': {
    resourceType: 'biz_user_equipment',
    kebab: 'biz-user-equipment',
    title: 'BizUserEquipment',
    columns: [
      {
        key: 'user_id',
        label: 'User Id',
        type: 'number',
        required: true,
        filterable: false,
        formable: true,
      },
      {
        key: 'avatar_cosmetic_id',
        label: 'Avatar Cosmetic Id',
        type: 'fk',
        required: false,
        filterable: true,
        formable: true,
      },
      {
        key: 'avatar_frame_cosmetic_id',
        label: 'Avatar Frame Cosmetic Id',
        type: 'fk',
        required: false,
        filterable: true,
        formable: true,
      },
      {
        key: 'crown_cosmetic_id',
        label: 'Crown Cosmetic Id',
        type: 'fk',
        required: false,
        filterable: true,
        formable: true,
      },
      {
        key: 'badge_cosmetic_id',
        label: 'Badge Cosmetic Id',
        type: 'fk',
        required: false,
        filterable: true,
        formable: true,
      },
      {
        key: 'title_cosmetic_id',
        label: 'Title Cosmetic Id',
        type: 'fk',
        required: false,
        filterable: true,
        formable: true,
      },
      {
        key: 'name_effect_cosmetic_id',
        label: 'Name Effect Cosmetic Id',
        type: 'fk',
        required: false,
        filterable: true,
        formable: true,
      },
      {
        key: 'updated_at',
        label: 'Updated At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'id',
        label: 'Id',
        type: 'number',
        required: false,
        filterable: false,
        formable: false,
      },
    ],
  },
  'biz_user_growth_account': {
    resourceType: 'biz_user_growth_account',
    kebab: 'biz-user-growth-account',
    title: 'BizUserGrowthAccount',
    columns: [
      {
        key: 'user_id',
        label: 'User Id',
        type: 'number',
        required: true,
        filterable: false,
        formable: true,
      },
      {
        key: 'total_growth_points',
        label: 'Total Growth Points',
        type: 'number',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'current_level_id',
        label: 'Current Level Id',
        type: 'fk',
        required: false,
        filterable: true,
        formable: true,
      },
      {
        key: 'id',
        label: 'Id',
        type: 'number',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'created_at',
        label: 'Created At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'updated_at',
        label: 'Updated At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
    ],
  },
  'biz_user_growth_transaction': {
    resourceType: 'biz_user_growth_transaction',
    kebab: 'biz-user-growth-transaction',
    title: 'BizUserGrowthTransaction',
    columns: [
      {
        key: 'user_id',
        label: 'User Id',
        type: 'number',
        required: true,
        filterable: false,
        formable: true,
      },
      {
        key: 'change_points',
        label: 'Change Points',
        type: 'number',
        required: true,
        filterable: false,
        formable: true,
      },
      {
        key: 'balance_after',
        label: 'Balance After',
        type: 'number',
        required: true,
        filterable: false,
        formable: true,
      },
      {
        key: 'rule_id',
        label: 'Rule Id',
        type: 'fk',
        required: false,
        filterable: true,
        formable: true,
      },
      {
        key: 'source_type',
        label: 'Source Type',
        type: 'string',
        required: true,
        filterable: false,
        formable: true,
        maxLength: 64,
      },
      {
        key: 'source_id',
        label: 'Source Id',
        type: 'string',
        required: false,
        filterable: false,
        formable: true,
        maxLength: 128,
      },
      {
        key: 'event_id',
        label: 'Event Id',
        type: 'string',
        required: false,
        filterable: false,
        formable: true,
        maxLength: 128,
      },
      {
        key: 'transaction_type',
        label: 'Transaction Type',
        type: 'string',
        required: true,
        filterable: false,
        formable: true,
        maxLength: 32,
      },
      {
        key: 'description',
        label: 'Description',
        type: 'string',
        required: false,
        filterable: false,
        formable: true,
        maxLength: 500,
      },
      {
        key: 'operator_type',
        label: 'Operator Type',
        type: 'string',
        required: true,
        filterable: false,
        formable: true,
        maxLength: 32,
      },
      {
        key: 'operator_id',
        label: 'Operator Id',
        type: 'number',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'created_at',
        label: 'Created At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'id',
        label: 'Id',
        type: 'number',
        required: false,
        filterable: false,
        formable: false,
      },
    ],
  },
  'biz_user_level_benefit': {
    resourceType: 'biz_user_level_benefit',
    kebab: 'biz-user-level-benefit',
    title: 'BizUserLevelBenefit',
    columns: [
      {
        key: 'level_id',
        label: 'Level Id',
        type: 'fk',
        required: true,
        filterable: true,
        formable: true,
      },
      {
        key: 'benefit_type',
        label: 'Benefit Type',
        type: 'string',
        required: true,
        filterable: false,
        formable: true,
        maxLength: 64,
      },
      {
        key: 'benefit_code',
        label: 'Benefit Code',
        type: 'string',
        required: true,
        filterable: false,
        formable: true,
        maxLength: 128,
      },
      {
        key: 'benefit_value',
        label: 'Benefit Value',
        type: 'json',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'status',
        label: 'Status',
        type: 'string',
        required: false,
        filterable: true,
        formable: true,
        maxLength: 32,
      },
      {
        key: 'id',
        label: 'Id',
        type: 'number',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'created_at',
        label: 'Created At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'updated_at',
        label: 'Updated At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
    ],
  },
  'biz_user_level_history': {
    resourceType: 'biz_user_level_history',
    kebab: 'biz-user-level-history',
    title: 'BizUserLevelHistory',
    columns: [
      {
        key: 'user_id',
        label: 'User Id',
        type: 'number',
        required: true,
        filterable: false,
        formable: true,
      },
      {
        key: 'from_level_id',
        label: 'From Level Id',
        type: 'fk',
        required: false,
        filterable: true,
        formable: true,
      },
      {
        key: 'to_level_id',
        label: 'To Level Id',
        type: 'fk',
        required: true,
        filterable: true,
        formable: true,
      },
      {
        key: 'growth_points',
        label: 'Growth Points',
        type: 'number',
        required: true,
        filterable: false,
        formable: true,
      },
      {
        key: 'change_type',
        label: 'Change Type',
        type: 'string',
        required: true,
        filterable: false,
        formable: true,
        maxLength: 32,
      },
      {
        key: 'reason',
        label: 'Reason',
        type: 'string',
        required: false,
        filterable: false,
        formable: true,
        maxLength: 500,
      },
      {
        key: 'created_at',
        label: 'Created At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'id',
        label: 'Id',
        type: 'number',
        required: false,
        filterable: false,
        formable: false,
      },
    ],
  },
  'biz_user_point_account': {
    resourceType: 'biz_user_point_account',
    kebab: 'biz-user-point-account',
    title: 'BizUserPointAccount',
    columns: [
      {
        key: 'user_id',
        label: 'User Id',
        type: 'number',
        required: true,
        filterable: false,
        formable: true,
      },
      {
        key: 'total_earned_points',
        label: 'Total Earned Points',
        type: 'number',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'total_spent_points',
        label: 'Total Spent Points',
        type: 'number',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'balance_points',
        label: 'Balance Points',
        type: 'number',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'id',
        label: 'Id',
        type: 'number',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'created_at',
        label: 'Created At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'updated_at',
        label: 'Updated At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
    ],
  },
  'biz_user_point_transaction': {
    resourceType: 'biz_user_point_transaction',
    kebab: 'biz-user-point-transaction',
    title: 'BizUserPointTransaction',
    columns: [
      {
        key: 'user_id',
        label: 'User Id',
        type: 'number',
        required: true,
        filterable: false,
        formable: true,
      },
      {
        key: 'change_points',
        label: 'Change Points',
        type: 'number',
        required: true,
        filterable: false,
        formable: true,
      },
      {
        key: 'balance_after',
        label: 'Balance After',
        type: 'number',
        required: true,
        filterable: false,
        formable: true,
      },
      {
        key: 'rule_id',
        label: 'Rule Id',
        type: 'fk',
        required: false,
        filterable: true,
        formable: true,
      },
      {
        key: 'source_type',
        label: 'Source Type',
        type: 'string',
        required: true,
        filterable: false,
        formable: true,
        maxLength: 64,
      },
      {
        key: 'source_id',
        label: 'Source Id',
        type: 'string',
        required: false,
        filterable: false,
        formable: true,
        maxLength: 128,
      },
      {
        key: 'event_id',
        label: 'Event Id',
        type: 'string',
        required: false,
        filterable: false,
        formable: true,
        maxLength: 128,
      },
      {
        key: 'transaction_type',
        label: 'Transaction Type',
        type: 'string',
        required: true,
        filterable: false,
        formable: true,
        maxLength: 32,
      },
      {
        key: 'description',
        label: 'Description',
        type: 'string',
        required: false,
        filterable: false,
        formable: true,
        maxLength: 500,
      },
      {
        key: 'operator_type',
        label: 'Operator Type',
        type: 'string',
        required: true,
        filterable: false,
        formable: true,
        maxLength: 32,
      },
      {
        key: 'operator_id',
        label: 'Operator Id',
        type: 'number',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'created_at',
        label: 'Created At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'id',
        label: 'Id',
        type: 'number',
        required: false,
        filterable: false,
        formable: false,
      },
    ],
  },
  'biz_user_task': {
    resourceType: 'biz_user_task',
    kebab: 'biz-user-task',
    title: 'BizUserTask',
    columns: [
      {
        key: 'user_id',
        label: 'User Id',
        type: 'number',
        required: true,
        filterable: false,
        formable: true,
      },
      {
        key: 'task_id',
        label: 'Task Id',
        type: 'fk',
        required: true,
        filterable: true,
        formable: true,
      },
      {
        key: 'progress',
        label: 'Progress',
        type: 'number',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'status',
        label: 'Status',
        type: 'string',
        required: false,
        filterable: true,
        formable: true,
        maxLength: 32,
      },
      {
        key: 'completed_at',
        label: 'Completed At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'claimed_at',
        label: 'Claimed At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'created_at',
        label: 'Created At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'id',
        label: 'Id',
        type: 'number',
        required: false,
        filterable: false,
        formable: false,
      },
    ],
  },
  'tool': {
    resourceType: 'tool',
    kebab: 'tool',
    title: 'Tool',
    columns: [
      {
        key: 'category_id',
        label: 'Category Id',
        type: 'fk',
        required: true,
        filterable: true,
        formable: true,
      },
      {
        key: 'code',
        label: 'Code',
        type: 'string',
        required: true,
        filterable: true,
        formable: true,
        maxLength: 128,
      },
      {
        key: 'name',
        label: 'Name',
        type: 'string',
        required: true,
        filterable: false,
        formable: true,
        maxLength: 128,
      },
      {
        key: 'description',
        label: 'Description',
        type: 'string',
        required: false,
        filterable: false,
        formable: true,
        maxLength: 1000,
      },
      {
        key: 'component_key',
        label: 'Component Key',
        type: 'string',
        required: false,
        filterable: false,
        formable: true,
        maxLength: 128,
      },
      {
        key: 'execution_mode',
        label: 'Execution Mode',
        type: 'enum',
        required: true,
        filterable: false,
        formable: true,
        maxLength: 16,
        enumType: 'ToolExecutionMode',
      },
      {
        key: 'lifecycle_status',
        label: 'Lifecycle Status',
        type: 'enum',
        required: false,
        filterable: false,
        formable: true,
        maxLength: 16,
        enumType: 'ToolLifecycleStatus',
      },
      {
        key: 'visibility',
        label: 'Visibility',
        type: 'string',
        required: false,
        filterable: true,
        formable: true,
        maxLength: 32,
      },
      {
        key: 'sort_order',
        label: 'Sort Order',
        type: 'number',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'is_recommended',
        label: 'Is Recommended',
        type: 'boolean',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'tags',
        label: 'Tags',
        type: 'json',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'id',
        label: 'Id',
        type: 'number',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'created_at',
        label: 'Created At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'updated_at',
        label: 'Updated At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'deleted_at',
        label: 'Deleted At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
    ],
  },
  'tool_access_policy': {
    resourceType: 'tool_access_policy',
    kebab: 'tool-access-policy',
    title: 'ToolAccessPolicy',
    columns: [
      {
        key: 'tool_id',
        label: 'Tool Id',
        type: 'fk',
        required: true,
        filterable: true,
        formable: true,
      },
      {
        key: 'subject_type',
        label: 'Subject Type',
        type: 'enum',
        required: true,
        filterable: false,
        formable: true,
        maxLength: 16,
        enumType: 'ToolAccessSubjectType',
      },
      {
        key: 'user_level_id',
        label: 'User Level Id',
        type: 'fk',
        required: false,
        filterable: true,
        formable: true,
      },
      {
        key: 'enabled',
        label: 'Enabled',
        type: 'boolean',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'quota_config',
        label: 'Quota Config',
        type: 'json',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'id',
        label: 'Id',
        type: 'number',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'created_at',
        label: 'Created At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'updated_at',
        label: 'Updated At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
    ],
  },
  'tool_category': {
    resourceType: 'tool_category',
    kebab: 'tool-category',
    title: 'ToolCategory',
    columns: [
      {
        key: 'parent_id',
        label: 'Parent Id',
        type: 'fk',
        required: false,
        filterable: true,
        formable: true,
      },
      {
        key: 'code',
        label: 'Code',
        type: 'string',
        required: true,
        filterable: true,
        formable: true,
        maxLength: 64,
      },
      {
        key: 'name',
        label: 'Name',
        type: 'string',
        required: true,
        filterable: false,
        formable: true,
        maxLength: 128,
      },
      {
        key: 'icon_url',
        label: 'Icon Url',
        type: 'string',
        required: false,
        filterable: false,
        formable: true,
        maxLength: 512,
      },
      {
        key: 'sort_order',
        label: 'Sort Order',
        type: 'number',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'status',
        label: 'Status',
        type: 'string',
        required: false,
        filterable: true,
        formable: true,
        maxLength: 32,
      },
      {
        key: 'id',
        label: 'Id',
        type: 'number',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'created_at',
        label: 'Created At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'updated_at',
        label: 'Updated At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'deleted_at',
        label: 'Deleted At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
    ],
  },
  'tool_component_registry': {
    resourceType: 'tool_component_registry',
    kebab: 'tool-component-registry',
    title: 'ToolComponentRegistry',
    columns: [
      {
        key: 'component_key',
        label: 'Component Key',
        type: 'string',
        required: true,
        filterable: false,
        formable: true,
        maxLength: 128,
      },
      {
        key: 'component_type',
        label: 'Component Type',
        type: 'string',
        required: true,
        filterable: false,
        formable: true,
        maxLength: 32,
      },
      {
        key: 'implementation_ref',
        label: 'Implementation Ref',
        type: 'string',
        required: true,
        filterable: false,
        formable: true,
        maxLength: 255,
      },
      {
        key: 'status',
        label: 'Status',
        type: 'string',
        required: false,
        filterable: true,
        formable: true,
        maxLength: 32,
      },
      {
        key: 'id',
        label: 'Id',
        type: 'number',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'created_at',
        label: 'Created At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'updated_at',
        label: 'Updated At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
    ],
  },
  'tool_popularity_daily': {
    resourceType: 'tool_popularity_daily',
    kebab: 'tool-popularity-daily',
    title: 'ToolPopularityDaily',
    columns: [
      {
        key: 'tool_id',
        label: 'Tool Id',
        type: 'number',
        required: true,
        filterable: false,
        formable: true,
      },
      {
        key: 'stat_date',
        label: 'Stat Date',
        type: 'date',
        required: true,
        filterable: false,
        formable: true,
      },
      {
        key: 'score',
        label: 'Score',
        type: 'number',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'rank_no',
        label: 'Rank No',
        type: 'number',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'id',
        label: 'Id',
        type: 'number',
        required: false,
        filterable: false,
        formable: false,
      },
    ],
  },
  'tool_recent_usage': {
    resourceType: 'tool_recent_usage',
    kebab: 'tool-recent-usage',
    title: 'ToolRecentUsage',
    columns: [
      {
        key: 'user_id',
        label: 'User Id',
        type: 'fk',
        required: true,
        filterable: true,
        formable: true,
      },
      {
        key: 'tool_id',
        label: 'Tool Id',
        type: 'fk',
        required: true,
        filterable: true,
        formable: true,
      },
      {
        key: 'last_used_at',
        label: 'Last Used At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'use_count',
        label: 'Use Count',
        type: 'number',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'id',
        label: 'Id',
        type: 'number',
        required: false,
        filterable: false,
        formable: false,
      },
    ],
  },
  'tool_usage_daily': {
    resourceType: 'tool_usage_daily',
    kebab: 'tool-usage-daily',
    title: 'ToolUsageDaily',
    columns: [
      {
        key: 'tool_id',
        label: 'Tool Id',
        type: 'number',
        required: true,
        filterable: false,
        formable: true,
      },
      {
        key: 'stat_date',
        label: 'Stat Date',
        type: 'date',
        required: true,
        filterable: false,
        formable: true,
      },
      {
        key: 'total_count',
        label: 'Total Count',
        type: 'number',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'success_count',
        label: 'Success Count',
        type: 'number',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'failure_count',
        label: 'Failure Count',
        type: 'number',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'guest_count',
        label: 'Guest Count',
        type: 'number',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'user_count',
        label: 'User Count',
        type: 'number',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'unique_user_count',
        label: 'Unique User Count',
        type: 'number',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'avg_duration_ms',
        label: 'Avg Duration Ms',
        type: 'number',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'id',
        label: 'Id',
        type: 'number',
        required: false,
        filterable: false,
        formable: false,
      },
    ],
  },
  'tool_usage_event': {
    resourceType: 'tool_usage_event',
    kebab: 'tool-usage-event',
    title: 'ToolUsageEvent',
    columns: [
      {
        key: 'tool_id',
        label: 'Tool Id',
        type: 'number',
        required: true,
        filterable: false,
        formable: true,
      },
      {
        key: 'user_id',
        label: 'User Id',
        type: 'fk',
        required: false,
        filterable: true,
        formable: true,
      },
      {
        key: 'anonymous_id_hash',
        label: 'Anonymous Id Hash',
        type: 'string',
        required: false,
        filterable: false,
        formable: true,
        maxLength: 128,
      },
      {
        key: 'result',
        label: 'Result',
        type: 'string',
        required: false,
        filterable: false,
        formable: true,
        maxLength: 32,
      },
      {
        key: 'duration_ms',
        label: 'Duration Ms',
        type: 'number',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'execution_mode',
        label: 'Execution Mode',
        type: 'string',
        required: false,
        filterable: false,
        formable: true,
        maxLength: 32,
      },
      {
        key: 'trace_id',
        label: 'Trace Id',
        type: 'string',
        required: false,
        filterable: false,
        formable: true,
        maxLength: 128,
      },
      {
        key: 'created_at',
        label: 'Created At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'id',
        label: 'Id',
        type: 'number',
        required: false,
        filterable: false,
        formable: false,
      },
    ],
  },
  'tool_version': {
    resourceType: 'tool_version',
    kebab: 'tool-version',
    title: 'ToolVersion',
    columns: [
      {
        key: 'tool_id',
        label: 'Tool Id',
        type: 'fk',
        required: true,
        filterable: true,
        formable: true,
      },
      {
        key: 'version',
        label: 'Version',
        type: 'string',
        required: true,
        filterable: false,
        formable: true,
        maxLength: 64,
      },
      {
        key: 'config',
        label: 'Config',
        type: 'json',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'status',
        label: 'Status',
        type: 'string',
        required: false,
        filterable: true,
        formable: true,
        maxLength: 32,
      },
      {
        key: 'published_at',
        label: 'Published At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'created_at',
        label: 'Created At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'id',
        label: 'Id',
        type: 'number',
        required: false,
        filterable: false,
        formable: false,
      },
    ],
  },
  'blog_article': {
    resourceType: 'blog_article',
    kebab: 'blog-article',
    title: 'BlogArticle',
    columns: [
      {
        key: 'author_id',
        label: 'Author Id',
        type: 'fk',
        required: true,
        filterable: true,
        formable: true,
      },
      {
        key: 'category_id',
        label: 'Category Id',
        type: 'fk',
        required: false,
        filterable: true,
        formable: true,
      },
      {
        key: 'title',
        label: 'Title',
        type: 'string',
        required: true,
        filterable: false,
        formable: true,
        maxLength: 255,
      },
      {
        key: 'slug',
        label: 'Slug',
        type: 'string',
        required: true,
        filterable: false,
        formable: true,
        maxLength: 255,
      },
      {
        key: 'summary',
        label: 'Summary',
        type: 'string',
        required: false,
        filterable: false,
        formable: true,
        maxLength: 1000,
      },
      {
        key: 'cover_url',
        label: 'Cover Url',
        type: 'string',
        required: false,
        filterable: false,
        formable: true,
        maxLength: 512,
      },
      {
        key: 'content',
        label: 'Content',
        type: 'string',
        required: true,
        filterable: false,
        formable: true,
      },
      {
        key: 'status',
        label: 'Status',
        type: 'enum',
        required: false,
        filterable: true,
        formable: true,
        maxLength: 16,
        enumType: 'BlogArticleStatus',
      },
      {
        key: 'published_at',
        label: 'Published At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'view_count',
        label: 'View Count',
        type: 'number',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'like_count',
        label: 'Like Count',
        type: 'number',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'favorite_count',
        label: 'Favorite Count',
        type: 'number',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'comment_count',
        label: 'Comment Count',
        type: 'number',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'id',
        label: 'Id',
        type: 'number',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'created_at',
        label: 'Created At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'updated_at',
        label: 'Updated At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'deleted_at',
        label: 'Deleted At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
    ],
  },
  'blog_article_tag': {
    resourceType: 'blog_article_tag',
    kebab: 'blog-article-tag',
    title: 'BlogArticleTag',
    columns: [
      {
        key: 'article_id',
        label: 'Article Id',
        type: 'fk',
        required: true,
        filterable: true,
        formable: true,
      },
      {
        key: 'tag_id',
        label: 'Tag Id',
        type: 'fk',
        required: true,
        filterable: true,
        formable: true,
      },
    ],
  },
  'blog_article_version': {
    resourceType: 'blog_article_version',
    kebab: 'blog-article-version',
    title: 'BlogArticleVersion',
    columns: [
      {
        key: 'article_id',
        label: 'Article Id',
        type: 'fk',
        required: true,
        filterable: true,
        formable: true,
      },
      {
        key: 'version_no',
        label: 'Version No',
        type: 'number',
        required: true,
        filterable: false,
        formable: true,
      },
      {
        key: 'title',
        label: 'Title',
        type: 'string',
        required: true,
        filterable: false,
        formable: true,
        maxLength: 255,
      },
      {
        key: 'summary',
        label: 'Summary',
        type: 'string',
        required: false,
        filterable: false,
        formable: true,
        maxLength: 1000,
      },
      {
        key: 'content',
        label: 'Content',
        type: 'string',
        required: true,
        filterable: false,
        formable: true,
      },
      {
        key: 'created_by',
        label: 'Created By',
        type: 'fk',
        required: false,
        filterable: true,
        formable: false,
      },
      {
        key: 'created_at',
        label: 'Created At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'id',
        label: 'Id',
        type: 'number',
        required: false,
        filterable: false,
        formable: false,
      },
    ],
  },
  'blog_author': {
    resourceType: 'blog_author',
    kebab: 'blog-author',
    title: 'BlogAuthor',
    columns: [
      {
        key: 'user_id',
        label: 'User Id',
        type: 'number',
        required: true,
        filterable: false,
        formable: true,
      },
      {
        key: 'author_name',
        label: 'Author Name',
        type: 'string',
        required: true,
        filterable: false,
        formable: true,
        maxLength: 128,
      },
      {
        key: 'status',
        label: 'Status',
        type: 'string',
        required: false,
        filterable: true,
        formable: true,
        maxLength: 32,
      },
      {
        key: 'approved_at',
        label: 'Approved At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'approved_by',
        label: 'Approved By',
        type: 'fk',
        required: false,
        filterable: true,
        formable: false,
      },
      {
        key: 'id',
        label: 'Id',
        type: 'number',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'created_at',
        label: 'Created At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'updated_at',
        label: 'Updated At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
    ],
  },
  'blog_author_application': {
    resourceType: 'blog_author_application',
    kebab: 'blog-author-application',
    title: 'BlogAuthorApplication',
    columns: [
      {
        key: 'user_id',
        label: 'User Id',
        type: 'fk',
        required: true,
        filterable: true,
        formable: true,
      },
      {
        key: 'application_reason',
        label: 'Application Reason',
        type: 'string',
        required: false,
        filterable: false,
        formable: true,
        maxLength: 2000,
      },
      {
        key: 'status',
        label: 'Status',
        type: 'enum',
        required: false,
        filterable: true,
        formable: true,
        maxLength: 16,
        enumType: 'BlogAuthorApplicationStatus',
      },
      {
        key: 'reviewed_by',
        label: 'Reviewed By',
        type: 'fk',
        required: false,
        filterable: true,
        formable: false,
      },
      {
        key: 'reviewed_at',
        label: 'Reviewed At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'review_remark',
        label: 'Review Remark',
        type: 'string',
        required: false,
        filterable: false,
        formable: true,
        maxLength: 1000,
      },
      {
        key: 'id',
        label: 'Id',
        type: 'number',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'created_at',
        label: 'Created At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'updated_at',
        label: 'Updated At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
    ],
  },
  'blog_category': {
    resourceType: 'blog_category',
    kebab: 'blog-category',
    title: 'BlogCategory',
    columns: [
      {
        key: 'parent_id',
        label: 'Parent Id',
        type: 'fk',
        required: false,
        filterable: true,
        formable: true,
      },
      {
        key: 'code',
        label: 'Code',
        type: 'string',
        required: true,
        filterable: true,
        formable: true,
        maxLength: 64,
      },
      {
        key: 'name',
        label: 'Name',
        type: 'string',
        required: true,
        filterable: false,
        formable: true,
        maxLength: 128,
      },
      {
        key: 'sort_order',
        label: 'Sort Order',
        type: 'number',
        required: false,
        filterable: false,
        formable: true,
      },
      {
        key: 'status',
        label: 'Status',
        type: 'string',
        required: false,
        filterable: true,
        formable: true,
        maxLength: 32,
      },
      {
        key: 'id',
        label: 'Id',
        type: 'number',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'created_at',
        label: 'Created At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'updated_at',
        label: 'Updated At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'deleted_at',
        label: 'Deleted At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
    ],
  },
  'blog_comment': {
    resourceType: 'blog_comment',
    kebab: 'blog-comment',
    title: 'BlogComment',
    columns: [
      {
        key: 'article_id',
        label: 'Article Id',
        type: 'fk',
        required: true,
        filterable: true,
        formable: true,
      },
      {
        key: 'user_id',
        label: 'User Id',
        type: 'fk',
        required: true,
        filterable: true,
        formable: true,
      },
      {
        key: 'parent_id',
        label: 'Parent Id',
        type: 'fk',
        required: false,
        filterable: true,
        formable: true,
      },
      {
        key: 'content',
        label: 'Content',
        type: 'string',
        required: true,
        filterable: false,
        formable: true,
      },
      {
        key: 'status',
        label: 'Status',
        type: 'string',
        required: false,
        filterable: true,
        formable: true,
        maxLength: 32,
      },
      {
        key: 'id',
        label: 'Id',
        type: 'number',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'created_at',
        label: 'Created At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'updated_at',
        label: 'Updated At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'deleted_at',
        label: 'Deleted At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
    ],
  },
  'blog_favorite': {
    resourceType: 'blog_favorite',
    kebab: 'blog-favorite',
    title: 'BlogFavorite',
    columns: [
      {
        key: 'user_id',
        label: 'User Id',
        type: 'fk',
        required: true,
        filterable: true,
        formable: true,
      },
      {
        key: 'article_id',
        label: 'Article Id',
        type: 'fk',
        required: true,
        filterable: true,
        formable: true,
      },
      {
        key: 'created_at',
        label: 'Created At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'id',
        label: 'Id',
        type: 'number',
        required: false,
        filterable: false,
        formable: false,
      },
    ],
  },
  'blog_like': {
    resourceType: 'blog_like',
    kebab: 'blog-like',
    title: 'BlogLike',
    columns: [
      {
        key: 'user_id',
        label: 'User Id',
        type: 'fk',
        required: true,
        filterable: true,
        formable: true,
      },
      {
        key: 'article_id',
        label: 'Article Id',
        type: 'fk',
        required: true,
        filterable: true,
        formable: true,
      },
      {
        key: 'created_at',
        label: 'Created At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'id',
        label: 'Id',
        type: 'number',
        required: false,
        filterable: false,
        formable: false,
      },
    ],
  },
  'blog_tag': {
    resourceType: 'blog_tag',
    kebab: 'blog-tag',
    title: 'BlogTag',
    columns: [
      {
        key: 'code',
        label: 'Code',
        type: 'string',
        required: true,
        filterable: true,
        formable: true,
        maxLength: 64,
      },
      {
        key: 'name',
        label: 'Name',
        type: 'string',
        required: true,
        filterable: false,
        formable: true,
        maxLength: 128,
      },
      {
        key: 'status',
        label: 'Status',
        type: 'string',
        required: false,
        filterable: true,
        formable: true,
        maxLength: 32,
      },
      {
        key: 'created_at',
        label: 'Created At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'id',
        label: 'Id',
        type: 'number',
        required: false,
        filterable: false,
        formable: false,
      },
    ],
  },
  'blog_user_follow': {
    resourceType: 'blog_user_follow',
    kebab: 'blog-user-follow',
    title: 'BlogUserFollow',
    columns: [
      {
        key: 'follower_user_id',
        label: 'Follower User Id',
        type: 'fk',
        required: true,
        filterable: true,
        formable: true,
      },
      {
        key: 'followed_user_id',
        label: 'Followed User Id',
        type: 'fk',
        required: true,
        filterable: true,
        formable: true,
      },
      {
        key: 'created_at',
        label: 'Created At',
        type: 'datetime',
        required: false,
        filterable: false,
        formable: false,
      },
      {
        key: 'id',
        label: 'Id',
        type: 'number',
        required: false,
        filterable: false,
        formable: false,
      },
    ],
  },
}

/**
 * `kebab`（路由段）→ 元数据。
 *
 * `GenericCrudView.vue` 被 44 个页面共用，靠路由路径反查自己是哪个资源 ——
 * 路由是 `/v31/<kebab>`，因此需要这张反查表，而不是让视图去遍历 `V31_META`。
 *
 * 值类型是 `V31ResourceMeta | undefined` 而不是 `V31ResourceMeta`：
 * 工程开了 `noUncheckedIndexedAccess`，索引访问本来就可能是 undefined，
 * 写成非空类型只会逼调用方在**视图**里加断言，把'查不到'这件事藏起来。
 */
export const V31_META_BY_KEBAB: Record<string, V31ResourceMeta | undefined> = {
  'biz-user': V31_META['biz_user'],
  'biz-user-level': V31_META['biz_user_level'],
  'biz-user-login-identity': V31_META['biz_user_login_identity'],
  'biz-user-login-log': V31_META['biz_user_login_log'],
  'biz-user-password-history': V31_META['biz_user_password_history'],
  'biz-user-profile': V31_META['biz_user_profile'],
  'biz-user-session': V31_META['biz_user_session'],
  'biz-user-verification': V31_META['biz_user_verification'],
  'biz-achievement': V31_META['biz_achievement'],
  'biz-cosmetic': V31_META['biz_cosmetic'],
  'biz-growth-event': V31_META['biz_growth_event'],
  'biz-growth-rule': V31_META['biz_growth_rule'],
  'biz-point-rule': V31_META['biz_point_rule'],
  'biz-task': V31_META['biz_task'],
  'biz-user-achievement': V31_META['biz_user_achievement'],
  'biz-user-cosmetic': V31_META['biz_user_cosmetic'],
  'biz-user-equipment': V31_META['biz_user_equipment'],
  'biz-user-growth-account': V31_META['biz_user_growth_account'],
  'biz-user-growth-transaction': V31_META['biz_user_growth_transaction'],
  'biz-user-level-benefit': V31_META['biz_user_level_benefit'],
  'biz-user-level-history': V31_META['biz_user_level_history'],
  'biz-user-point-account': V31_META['biz_user_point_account'],
  'biz-user-point-transaction': V31_META['biz_user_point_transaction'],
  'biz-user-task': V31_META['biz_user_task'],
  'tool': V31_META['tool'],
  'tool-access-policy': V31_META['tool_access_policy'],
  'tool-category': V31_META['tool_category'],
  'tool-component-registry': V31_META['tool_component_registry'],
  'tool-popularity-daily': V31_META['tool_popularity_daily'],
  'tool-recent-usage': V31_META['tool_recent_usage'],
  'tool-usage-daily': V31_META['tool_usage_daily'],
  'tool-usage-event': V31_META['tool_usage_event'],
  'tool-version': V31_META['tool_version'],
  'blog-article': V31_META['blog_article'],
  'blog-article-tag': V31_META['blog_article_tag'],
  'blog-article-version': V31_META['blog_article_version'],
  'blog-author': V31_META['blog_author'],
  'blog-author-application': V31_META['blog_author_application'],
  'blog-category': V31_META['blog_category'],
  'blog-comment': V31_META['blog_comment'],
  'blog-favorite': V31_META['blog_favorite'],
  'blog-like': V31_META['blog_like'],
  'blog-tag': V31_META['blog_tag'],
  'blog-user-follow': V31_META['blog_user_follow'],
}
