/**
 * V3.1 四新增域页面夹具片段（VCTN §33，自动生成）。
 *
 * 导出 `V31_PAGE_SPECS` 供 `tests/helpers/fixtures.ts` 摊平进 `FULL_PAGE_SPECS`。
 * 与后端 `scripts/_v31_seed.py` 出自同一次生成，因此两边不会漂移。
 *
 * ⚠️ 本文件由 `scripts/gen_v31_crud.py` 覆盖生成，不要手改。
 */

import type { PermissionPageItem } from '@/types'

export const V31_PAGE_SPECS: PermissionPageItem[] = [
  {
    id: 'v31-biz_user',
    code: 'v31:biz-user:page',
    name: 'BizUser',
    route_path: '/v31/biz-user',
    component_path: '/crud/generic',
    sort_order: 1000,
  },
  {
    id: 'v31-biz_user_level',
    code: 'v31:biz-user-level:page',
    name: 'BizUserLevel',
    route_path: '/v31/biz-user-level',
    component_path: '/crud/generic',
    sort_order: 1001,
  },
  {
    id: 'v31-biz_user_login_identity',
    code: 'v31:biz-user-login-identity:page',
    name: 'BizUserLoginIdentity',
    route_path: '/v31/biz-user-login-identity',
    component_path: '/crud/generic',
    sort_order: 1002,
  },
  {
    id: 'v31-biz_user_login_log',
    code: 'v31:biz-user-login-log:page',
    name: 'BizUserLoginLog',
    route_path: '/v31/biz-user-login-log',
    component_path: '/crud/generic',
    sort_order: 1003,
  },
  {
    id: 'v31-biz_user_password_history',
    code: 'v31:biz-user-password-history:page',
    name: 'BizUserPasswordHistory',
    route_path: '/v31/biz-user-password-history',
    component_path: '/crud/generic',
    sort_order: 1004,
  },
  {
    id: 'v31-biz_user_profile',
    code: 'v31:biz-user-profile:page',
    name: 'BizUserProfile',
    route_path: '/v31/biz-user-profile',
    component_path: '/crud/generic',
    sort_order: 1005,
  },
  {
    id: 'v31-biz_user_session',
    code: 'v31:biz-user-session:page',
    name: 'BizUserSession',
    route_path: '/v31/biz-user-session',
    component_path: '/crud/generic',
    sort_order: 1006,
  },
  {
    id: 'v31-biz_user_verification',
    code: 'v31:biz-user-verification:page',
    name: 'BizUserVerification',
    route_path: '/v31/biz-user-verification',
    component_path: '/crud/generic',
    sort_order: 1007,
  },
  {
    id: 'v31-biz_achievement',
    code: 'v31:biz-achievement:page',
    name: 'BizAchievement',
    route_path: '/v31/biz-achievement',
    component_path: '/crud/generic',
    sort_order: 1008,
  },
  {
    id: 'v31-biz_cosmetic',
    code: 'v31:biz-cosmetic:page',
    name: 'BizCosmetic',
    route_path: '/v31/biz-cosmetic',
    component_path: '/crud/generic',
    sort_order: 1009,
  },
  {
    id: 'v31-biz_growth_event',
    code: 'v31:biz-growth-event:page',
    name: 'BizGrowthEvent',
    route_path: '/v31/biz-growth-event',
    component_path: '/crud/generic',
    sort_order: 1010,
  },
  {
    id: 'v31-biz_growth_rule',
    code: 'v31:biz-growth-rule:page',
    name: 'BizGrowthRule',
    route_path: '/v31/biz-growth-rule',
    component_path: '/crud/generic',
    sort_order: 1011,
  },
  {
    id: 'v31-biz_point_rule',
    code: 'v31:biz-point-rule:page',
    name: 'BizPointRule',
    route_path: '/v31/biz-point-rule',
    component_path: '/crud/generic',
    sort_order: 1012,
  },
  {
    id: 'v31-biz_task',
    code: 'v31:biz-task:page',
    name: 'BizTask',
    route_path: '/v31/biz-task',
    component_path: '/crud/generic',
    sort_order: 1013,
  },
  {
    id: 'v31-biz_user_achievement',
    code: 'v31:biz-user-achievement:page',
    name: 'BizUserAchievement',
    route_path: '/v31/biz-user-achievement',
    component_path: '/crud/generic',
    sort_order: 1014,
  },
  {
    id: 'v31-biz_user_cosmetic',
    code: 'v31:biz-user-cosmetic:page',
    name: 'BizUserCosmetic',
    route_path: '/v31/biz-user-cosmetic',
    component_path: '/crud/generic',
    sort_order: 1015,
  },
  {
    id: 'v31-biz_user_equipment',
    code: 'v31:biz-user-equipment:page',
    name: 'BizUserEquipment',
    route_path: '/v31/biz-user-equipment',
    component_path: '/crud/generic',
    sort_order: 1016,
  },
  {
    id: 'v31-biz_user_growth_account',
    code: 'v31:biz-user-growth-account:page',
    name: 'BizUserGrowthAccount',
    route_path: '/v31/biz-user-growth-account',
    component_path: '/crud/generic',
    sort_order: 1017,
  },
  {
    id: 'v31-biz_user_growth_transaction',
    code: 'v31:biz-user-growth-transaction:page',
    name: 'BizUserGrowthTransaction',
    route_path: '/v31/biz-user-growth-transaction',
    component_path: '/crud/generic',
    sort_order: 1018,
  },
  {
    id: 'v31-biz_user_level_benefit',
    code: 'v31:biz-user-level-benefit:page',
    name: 'BizUserLevelBenefit',
    route_path: '/v31/biz-user-level-benefit',
    component_path: '/crud/generic',
    sort_order: 1019,
  },
  {
    id: 'v31-biz_user_level_history',
    code: 'v31:biz-user-level-history:page',
    name: 'BizUserLevelHistory',
    route_path: '/v31/biz-user-level-history',
    component_path: '/crud/generic',
    sort_order: 1020,
  },
  {
    id: 'v31-biz_user_point_account',
    code: 'v31:biz-user-point-account:page',
    name: 'BizUserPointAccount',
    route_path: '/v31/biz-user-point-account',
    component_path: '/crud/generic',
    sort_order: 1021,
  },
  {
    id: 'v31-biz_user_point_transaction',
    code: 'v31:biz-user-point-transaction:page',
    name: 'BizUserPointTransaction',
    route_path: '/v31/biz-user-point-transaction',
    component_path: '/crud/generic',
    sort_order: 1022,
  },
  {
    id: 'v31-biz_user_task',
    code: 'v31:biz-user-task:page',
    name: 'BizUserTask',
    route_path: '/v31/biz-user-task',
    component_path: '/crud/generic',
    sort_order: 1023,
  },
  {
    id: 'v31-tool',
    code: 'v31:tool:page',
    name: 'Tool',
    route_path: '/v31/tool',
    component_path: '/crud/generic',
    sort_order: 1024,
  },
  {
    id: 'v31-tool_access_policy',
    code: 'v31:tool-access-policy:page',
    name: 'ToolAccessPolicy',
    route_path: '/v31/tool-access-policy',
    component_path: '/crud/generic',
    sort_order: 1025,
  },
  {
    id: 'v31-tool_category',
    code: 'v31:tool-category:page',
    name: 'ToolCategory',
    route_path: '/v31/tool-category',
    component_path: '/crud/generic',
    sort_order: 1026,
  },
  {
    id: 'v31-tool_component_registry',
    code: 'v31:tool-component-registry:page',
    name: 'ToolComponentRegistry',
    route_path: '/v31/tool-component-registry',
    component_path: '/crud/generic',
    sort_order: 1027,
  },
  {
    id: 'v31-tool_popularity_daily',
    code: 'v31:tool-popularity-daily:page',
    name: 'ToolPopularityDaily',
    route_path: '/v31/tool-popularity-daily',
    component_path: '/crud/generic',
    sort_order: 1028,
  },
  {
    id: 'v31-tool_recent_usage',
    code: 'v31:tool-recent-usage:page',
    name: 'ToolRecentUsage',
    route_path: '/v31/tool-recent-usage',
    component_path: '/crud/generic',
    sort_order: 1029,
  },
  {
    id: 'v31-tool_usage_daily',
    code: 'v31:tool-usage-daily:page',
    name: 'ToolUsageDaily',
    route_path: '/v31/tool-usage-daily',
    component_path: '/crud/generic',
    sort_order: 1030,
  },
  {
    id: 'v31-tool_usage_event',
    code: 'v31:tool-usage-event:page',
    name: 'ToolUsageEvent',
    route_path: '/v31/tool-usage-event',
    component_path: '/crud/generic',
    sort_order: 1031,
  },
  {
    id: 'v31-tool_version',
    code: 'v31:tool-version:page',
    name: 'ToolVersion',
    route_path: '/v31/tool-version',
    component_path: '/crud/generic',
    sort_order: 1032,
  },
  {
    id: 'v31-blog_article',
    code: 'v31:blog-article:page',
    name: 'BlogArticle',
    route_path: '/v31/blog-article',
    component_path: '/crud/generic',
    sort_order: 1033,
  },
  {
    id: 'v31-blog_article_tag',
    code: 'v31:blog-article-tag:page',
    name: 'BlogArticleTag',
    route_path: '/v31/blog-article-tag',
    component_path: '/crud/generic',
    sort_order: 1034,
  },
  {
    id: 'v31-blog_article_version',
    code: 'v31:blog-article-version:page',
    name: 'BlogArticleVersion',
    route_path: '/v31/blog-article-version',
    component_path: '/crud/generic',
    sort_order: 1035,
  },
  {
    id: 'v31-blog_author',
    code: 'v31:blog-author:page',
    name: 'BlogAuthor',
    route_path: '/v31/blog-author',
    component_path: '/crud/generic',
    sort_order: 1036,
  },
  {
    id: 'v31-blog_author_application',
    code: 'v31:blog-author-application:page',
    name: 'BlogAuthorApplication',
    route_path: '/v31/blog-author-application',
    component_path: '/crud/generic',
    sort_order: 1037,
  },
  {
    id: 'v31-blog_category',
    code: 'v31:blog-category:page',
    name: 'BlogCategory',
    route_path: '/v31/blog-category',
    component_path: '/crud/generic',
    sort_order: 1038,
  },
  {
    id: 'v31-blog_comment',
    code: 'v31:blog-comment:page',
    name: 'BlogComment',
    route_path: '/v31/blog-comment',
    component_path: '/crud/generic',
    sort_order: 1039,
  },
  {
    id: 'v31-blog_favorite',
    code: 'v31:blog-favorite:page',
    name: 'BlogFavorite',
    route_path: '/v31/blog-favorite',
    component_path: '/crud/generic',
    sort_order: 1040,
  },
  {
    id: 'v31-blog_like',
    code: 'v31:blog-like:page',
    name: 'BlogLike',
    route_path: '/v31/blog-like',
    component_path: '/crud/generic',
    sort_order: 1041,
  },
  {
    id: 'v31-blog_tag',
    code: 'v31:blog-tag:page',
    name: 'BlogTag',
    route_path: '/v31/blog-tag',
    component_path: '/crud/generic',
    sort_order: 1042,
  },
  {
    id: 'v31-blog_user_follow',
    code: 'v31:blog-user-follow:page',
    name: 'BlogUserFollow',
    route_path: '/v31/blog-user-follow',
    component_path: '/crud/generic',
    sort_order: 1043,
  },
]
