"""V3.1 四新增域权限资源片段（VCTN §33，自动生成）。

由 `scripts/gen_v31_crud.py` 生成；`seed_data.py` 在本文件之后 extend 主清单。
"""

from __future__ import annotations

# (code, name, route_path, component_path, sort_order)
V31_PAGES: list[tuple[str, str, str, str, int]] = [
    ("v31:biz-user:page", "BizUser", "/v31/biz-user", "crud/generic", 1000),
    ("v31:biz-user-level:page", "BizUserLevel", "/v31/biz-user-level", "crud/generic", 1001),
    (
        "v31:biz-user-login-identity:page",
        "BizUserLoginIdentity",
        "/v31/biz-user-login-identity",
        "crud/generic",
        1002,
    ),
    (
        "v31:biz-user-login-log:page",
        "BizUserLoginLog",
        "/v31/biz-user-login-log",
        "crud/generic",
        1003,
    ),
    (
        "v31:biz-user-password-history:page",
        "BizUserPasswordHistory",
        "/v31/biz-user-password-history",
        "crud/generic",
        1004,
    ),
    ("v31:biz-user-profile:page", "BizUserProfile", "/v31/biz-user-profile", "crud/generic", 1005),
    ("v31:biz-user-session:page", "BizUserSession", "/v31/biz-user-session", "crud/generic", 1006),
    (
        "v31:biz-user-verification:page",
        "BizUserVerification",
        "/v31/biz-user-verification",
        "crud/generic",
        1007,
    ),
    ("v31:biz-achievement:page", "BizAchievement", "/v31/biz-achievement", "crud/generic", 1008),
    ("v31:biz-cosmetic:page", "BizCosmetic", "/v31/biz-cosmetic", "crud/generic", 1009),
    ("v31:biz-growth-event:page", "BizGrowthEvent", "/v31/biz-growth-event", "crud/generic", 1010),
    ("v31:biz-growth-rule:page", "BizGrowthRule", "/v31/biz-growth-rule", "crud/generic", 1011),
    ("v31:biz-point-rule:page", "BizPointRule", "/v31/biz-point-rule", "crud/generic", 1012),
    ("v31:biz-task:page", "BizTask", "/v31/biz-task", "crud/generic", 1013),
    (
        "v31:biz-user-achievement:page",
        "BizUserAchievement",
        "/v31/biz-user-achievement",
        "crud/generic",
        1014,
    ),
    (
        "v31:biz-user-cosmetic:page",
        "BizUserCosmetic",
        "/v31/biz-user-cosmetic",
        "crud/generic",
        1015,
    ),
    (
        "v31:biz-user-equipment:page",
        "BizUserEquipment",
        "/v31/biz-user-equipment",
        "crud/generic",
        1016,
    ),
    (
        "v31:biz-user-growth-account:page",
        "BizUserGrowthAccount",
        "/v31/biz-user-growth-account",
        "crud/generic",
        1017,
    ),
    (
        "v31:biz-user-growth-transaction:page",
        "BizUserGrowthTransaction",
        "/v31/biz-user-growth-transaction",
        "crud/generic",
        1018,
    ),
    (
        "v31:biz-user-level-benefit:page",
        "BizUserLevelBenefit",
        "/v31/biz-user-level-benefit",
        "crud/generic",
        1019,
    ),
    (
        "v31:biz-user-level-history:page",
        "BizUserLevelHistory",
        "/v31/biz-user-level-history",
        "crud/generic",
        1020,
    ),
    (
        "v31:biz-user-point-account:page",
        "BizUserPointAccount",
        "/v31/biz-user-point-account",
        "crud/generic",
        1021,
    ),
    (
        "v31:biz-user-point-transaction:page",
        "BizUserPointTransaction",
        "/v31/biz-user-point-transaction",
        "crud/generic",
        1022,
    ),
    ("v31:biz-user-task:page", "BizUserTask", "/v31/biz-user-task", "crud/generic", 1023),
    ("v31:tool:page", "Tool", "/v31/tool", "crud/generic", 1024),
    (
        "v31:tool-access-policy:page",
        "ToolAccessPolicy",
        "/v31/tool-access-policy",
        "crud/generic",
        1025,
    ),
    ("v31:tool-category:page", "ToolCategory", "/v31/tool-category", "crud/generic", 1026),
    (
        "v31:tool-component-registry:page",
        "ToolComponentRegistry",
        "/v31/tool-component-registry",
        "crud/generic",
        1027,
    ),
    (
        "v31:tool-popularity-daily:page",
        "ToolPopularityDaily",
        "/v31/tool-popularity-daily",
        "crud/generic",
        1028,
    ),
    (
        "v31:tool-recent-usage:page",
        "ToolRecentUsage",
        "/v31/tool-recent-usage",
        "crud/generic",
        1029,
    ),
    ("v31:tool-usage-daily:page", "ToolUsageDaily", "/v31/tool-usage-daily", "crud/generic", 1030),
    ("v31:tool-usage-event:page", "ToolUsageEvent", "/v31/tool-usage-event", "crud/generic", 1031),
    ("v31:tool-version:page", "ToolVersion", "/v31/tool-version", "crud/generic", 1032),
    ("v31:blog-article:page", "BlogArticle", "/v31/blog-article", "crud/generic", 1033),
    ("v31:blog-article-tag:page", "BlogArticleTag", "/v31/blog-article-tag", "crud/generic", 1034),
    (
        "v31:blog-article-version:page",
        "BlogArticleVersion",
        "/v31/blog-article-version",
        "crud/generic",
        1035,
    ),
    ("v31:blog-author:page", "BlogAuthor", "/v31/blog-author", "crud/generic", 1036),
    (
        "v31:blog-author-application:page",
        "BlogAuthorApplication",
        "/v31/blog-author-application",
        "crud/generic",
        1037,
    ),
    ("v31:blog-category:page", "BlogCategory", "/v31/blog-category", "crud/generic", 1038),
    ("v31:blog-comment:page", "BlogComment", "/v31/blog-comment", "crud/generic", 1039),
    ("v31:blog-favorite:page", "BlogFavorite", "/v31/blog-favorite", "crud/generic", 1040),
    ("v31:blog-like:page", "BlogLike", "/v31/blog-like", "crud/generic", 1041),
    ("v31:blog-tag:page", "BlogTag", "/v31/blog-tag", "crud/generic", 1042),
    ("v31:blog-user-follow:page", "BlogUserFollow", "/v31/blog-user-follow", "crud/generic", 1043),
]

# (code, name, parent_code, icon, order)
V31_MENUS: list[tuple[str, str, str | None, str | None, int]] = [
    ("v31:root", "V3.1 管理", None, "setting", 900),
    ("v31:domain:biz_user", "统一业务用户", "v31:root", None, 1010),
    ("v31:biz-user", "BizUser", "v31:domain:biz_user", None, 10),
    ("v31:biz-user-level", "BizUserLevel", "v31:domain:biz_user", None, 20),
    ("v31:biz-user-login-identity", "BizUserLoginIdentity", "v31:domain:biz_user", None, 30),
    ("v31:biz-user-login-log", "BizUserLoginLog", "v31:domain:biz_user", None, 40),
    ("v31:biz-user-password-history", "BizUserPasswordHistory", "v31:domain:biz_user", None, 50),
    ("v31:biz-user-profile", "BizUserProfile", "v31:domain:biz_user", None, 60),
    ("v31:biz-user-session", "BizUserSession", "v31:domain:biz_user", None, 70),
    ("v31:biz-user-verification", "BizUserVerification", "v31:domain:biz_user", None, 80),
    ("v31:domain:growth", "用户成长中心", "v31:root", None, 1020),
    ("v31:biz-achievement", "BizAchievement", "v31:domain:growth", None, 10),
    ("v31:biz-cosmetic", "BizCosmetic", "v31:domain:growth", None, 20),
    ("v31:biz-growth-event", "BizGrowthEvent", "v31:domain:growth", None, 30),
    ("v31:biz-growth-rule", "BizGrowthRule", "v31:domain:growth", None, 40),
    ("v31:biz-point-rule", "BizPointRule", "v31:domain:growth", None, 50),
    ("v31:biz-task", "BizTask", "v31:domain:growth", None, 60),
    ("v31:biz-user-achievement", "BizUserAchievement", "v31:domain:growth", None, 70),
    ("v31:biz-user-cosmetic", "BizUserCosmetic", "v31:domain:growth", None, 80),
    ("v31:biz-user-equipment", "BizUserEquipment", "v31:domain:growth", None, 90),
    ("v31:biz-user-growth-account", "BizUserGrowthAccount", "v31:domain:growth", None, 100),
    ("v31:biz-user-growth-transaction", "BizUserGrowthTransaction", "v31:domain:growth", None, 110),
    ("v31:biz-user-level-benefit", "BizUserLevelBenefit", "v31:domain:growth", None, 120),
    ("v31:biz-user-level-history", "BizUserLevelHistory", "v31:domain:growth", None, 130),
    ("v31:biz-user-point-account", "BizUserPointAccount", "v31:domain:growth", None, 140),
    ("v31:biz-user-point-transaction", "BizUserPointTransaction", "v31:domain:growth", None, 150),
    ("v31:biz-user-task", "BizUserTask", "v31:domain:growth", None, 160),
    ("v31:domain:tool", "Tools 工具", "v31:root", None, 1030),
    ("v31:tool", "Tool", "v31:domain:tool", None, 10),
    ("v31:tool-access-policy", "ToolAccessPolicy", "v31:domain:tool", None, 20),
    ("v31:tool-category", "ToolCategory", "v31:domain:tool", None, 30),
    ("v31:tool-component-registry", "ToolComponentRegistry", "v31:domain:tool", None, 40),
    ("v31:tool-popularity-daily", "ToolPopularityDaily", "v31:domain:tool", None, 50),
    ("v31:tool-recent-usage", "ToolRecentUsage", "v31:domain:tool", None, 60),
    ("v31:tool-usage-daily", "ToolUsageDaily", "v31:domain:tool", None, 70),
    ("v31:tool-usage-event", "ToolUsageEvent", "v31:domain:tool", None, 80),
    ("v31:tool-version", "ToolVersion", "v31:domain:tool", None, 90),
    ("v31:domain:blog", "Blog 博客", "v31:root", None, 1040),
    ("v31:blog-article", "BlogArticle", "v31:domain:blog", None, 10),
    ("v31:blog-article-tag", "BlogArticleTag", "v31:domain:blog", None, 20),
    ("v31:blog-article-version", "BlogArticleVersion", "v31:domain:blog", None, 30),
    ("v31:blog-author", "BlogAuthor", "v31:domain:blog", None, 40),
    ("v31:blog-author-application", "BlogAuthorApplication", "v31:domain:blog", None, 50),
    ("v31:blog-category", "BlogCategory", "v31:domain:blog", None, 60),
    ("v31:blog-comment", "BlogComment", "v31:domain:blog", None, 70),
    ("v31:blog-favorite", "BlogFavorite", "v31:domain:blog", None, 80),
    ("v31:blog-like", "BlogLike", "v31:domain:blog", None, 90),
    ("v31:blog-tag", "BlogTag", "v31:domain:blog", None, 100),
    ("v31:blog-user-follow", "BlogUserFollow", "v31:domain:blog", None, 110),
]

# (menu_code, page_code)
V31_MENU_PAGES: list[tuple[str, str]] = [
    ("v31:biz-user", "v31:biz-user:page"),
    ("v31:biz-user-level", "v31:biz-user-level:page"),
    ("v31:biz-user-login-identity", "v31:biz-user-login-identity:page"),
    ("v31:biz-user-login-log", "v31:biz-user-login-log:page"),
    ("v31:biz-user-password-history", "v31:biz-user-password-history:page"),
    ("v31:biz-user-profile", "v31:biz-user-profile:page"),
    ("v31:biz-user-session", "v31:biz-user-session:page"),
    ("v31:biz-user-verification", "v31:biz-user-verification:page"),
    ("v31:biz-achievement", "v31:biz-achievement:page"),
    ("v31:biz-cosmetic", "v31:biz-cosmetic:page"),
    ("v31:biz-growth-event", "v31:biz-growth-event:page"),
    ("v31:biz-growth-rule", "v31:biz-growth-rule:page"),
    ("v31:biz-point-rule", "v31:biz-point-rule:page"),
    ("v31:biz-task", "v31:biz-task:page"),
    ("v31:biz-user-achievement", "v31:biz-user-achievement:page"),
    ("v31:biz-user-cosmetic", "v31:biz-user-cosmetic:page"),
    ("v31:biz-user-equipment", "v31:biz-user-equipment:page"),
    ("v31:biz-user-growth-account", "v31:biz-user-growth-account:page"),
    ("v31:biz-user-growth-transaction", "v31:biz-user-growth-transaction:page"),
    ("v31:biz-user-level-benefit", "v31:biz-user-level-benefit:page"),
    ("v31:biz-user-level-history", "v31:biz-user-level-history:page"),
    ("v31:biz-user-point-account", "v31:biz-user-point-account:page"),
    ("v31:biz-user-point-transaction", "v31:biz-user-point-transaction:page"),
    ("v31:biz-user-task", "v31:biz-user-task:page"),
    ("v31:tool", "v31:tool:page"),
    ("v31:tool-access-policy", "v31:tool-access-policy:page"),
    ("v31:tool-category", "v31:tool-category:page"),
    ("v31:tool-component-registry", "v31:tool-component-registry:page"),
    ("v31:tool-popularity-daily", "v31:tool-popularity-daily:page"),
    ("v31:tool-recent-usage", "v31:tool-recent-usage:page"),
    ("v31:tool-usage-daily", "v31:tool-usage-daily:page"),
    ("v31:tool-usage-event", "v31:tool-usage-event:page"),
    ("v31:tool-version", "v31:tool-version:page"),
    ("v31:blog-article", "v31:blog-article:page"),
    ("v31:blog-article-tag", "v31:blog-article-tag:page"),
    ("v31:blog-article-version", "v31:blog-article-version:page"),
    ("v31:blog-author", "v31:blog-author:page"),
    ("v31:blog-author-application", "v31:blog-author-application:page"),
    ("v31:blog-category", "v31:blog-category:page"),
    ("v31:blog-comment", "v31:blog-comment:page"),
    ("v31:blog-favorite", "v31:blog-favorite:page"),
    ("v31:blog-like", "v31:blog-like:page"),
    ("v31:blog-tag", "v31:blog-tag:page"),
    ("v31:blog-user-follow", "v31:blog-user-follow:page"),
]

# (code, name, page_code)
V31_BUTTONS: list[tuple[str, str, str]] = [
    ("v31:biz-user:create", "新增BizUser", "v31:biz-user:page"),
    ("v31:biz-user:update", "编辑BizUser", "v31:biz-user:page"),
    ("v31:biz-user:delete", "删除BizUser", "v31:biz-user:page"),
    ("v31:biz-user-level:create", "新增BizUserLevel", "v31:biz-user-level:page"),
    ("v31:biz-user-level:update", "编辑BizUserLevel", "v31:biz-user-level:page"),
    ("v31:biz-user-level:delete", "删除BizUserLevel", "v31:biz-user-level:page"),
    (
        "v31:biz-user-login-identity:create",
        "新增BizUserLoginIdentity",
        "v31:biz-user-login-identity:page",
    ),
    (
        "v31:biz-user-login-identity:update",
        "编辑BizUserLoginIdentity",
        "v31:biz-user-login-identity:page",
    ),
    (
        "v31:biz-user-login-identity:delete",
        "删除BizUserLoginIdentity",
        "v31:biz-user-login-identity:page",
    ),
    ("v31:biz-user-login-log:create", "新增BizUserLoginLog", "v31:biz-user-login-log:page"),
    ("v31:biz-user-login-log:update", "编辑BizUserLoginLog", "v31:biz-user-login-log:page"),
    ("v31:biz-user-login-log:delete", "删除BizUserLoginLog", "v31:biz-user-login-log:page"),
    (
        "v31:biz-user-password-history:create",
        "新增BizUserPasswordHistory",
        "v31:biz-user-password-history:page",
    ),
    (
        "v31:biz-user-password-history:update",
        "编辑BizUserPasswordHistory",
        "v31:biz-user-password-history:page",
    ),
    (
        "v31:biz-user-password-history:delete",
        "删除BizUserPasswordHistory",
        "v31:biz-user-password-history:page",
    ),
    ("v31:biz-user-profile:create", "新增BizUserProfile", "v31:biz-user-profile:page"),
    ("v31:biz-user-profile:update", "编辑BizUserProfile", "v31:biz-user-profile:page"),
    ("v31:biz-user-profile:delete", "删除BizUserProfile", "v31:biz-user-profile:page"),
    ("v31:biz-user-session:create", "新增BizUserSession", "v31:biz-user-session:page"),
    ("v31:biz-user-session:update", "编辑BizUserSession", "v31:biz-user-session:page"),
    ("v31:biz-user-session:delete", "删除BizUserSession", "v31:biz-user-session:page"),
    (
        "v31:biz-user-verification:create",
        "新增BizUserVerification",
        "v31:biz-user-verification:page",
    ),
    (
        "v31:biz-user-verification:update",
        "编辑BizUserVerification",
        "v31:biz-user-verification:page",
    ),
    (
        "v31:biz-user-verification:delete",
        "删除BizUserVerification",
        "v31:biz-user-verification:page",
    ),
    ("v31:biz-achievement:create", "新增BizAchievement", "v31:biz-achievement:page"),
    ("v31:biz-achievement:update", "编辑BizAchievement", "v31:biz-achievement:page"),
    ("v31:biz-achievement:delete", "删除BizAchievement", "v31:biz-achievement:page"),
    ("v31:biz-cosmetic:create", "新增BizCosmetic", "v31:biz-cosmetic:page"),
    ("v31:biz-cosmetic:update", "编辑BizCosmetic", "v31:biz-cosmetic:page"),
    ("v31:biz-cosmetic:delete", "删除BizCosmetic", "v31:biz-cosmetic:page"),
    ("v31:biz-growth-event:create", "新增BizGrowthEvent", "v31:biz-growth-event:page"),
    ("v31:biz-growth-event:update", "编辑BizGrowthEvent", "v31:biz-growth-event:page"),
    ("v31:biz-growth-event:delete", "删除BizGrowthEvent", "v31:biz-growth-event:page"),
    ("v31:biz-growth-rule:create", "新增BizGrowthRule", "v31:biz-growth-rule:page"),
    ("v31:biz-growth-rule:update", "编辑BizGrowthRule", "v31:biz-growth-rule:page"),
    ("v31:biz-growth-rule:delete", "删除BizGrowthRule", "v31:biz-growth-rule:page"),
    ("v31:biz-point-rule:create", "新增BizPointRule", "v31:biz-point-rule:page"),
    ("v31:biz-point-rule:update", "编辑BizPointRule", "v31:biz-point-rule:page"),
    ("v31:biz-point-rule:delete", "删除BizPointRule", "v31:biz-point-rule:page"),
    ("v31:biz-task:create", "新增BizTask", "v31:biz-task:page"),
    ("v31:biz-task:update", "编辑BizTask", "v31:biz-task:page"),
    ("v31:biz-task:delete", "删除BizTask", "v31:biz-task:page"),
    ("v31:biz-user-achievement:create", "新增BizUserAchievement", "v31:biz-user-achievement:page"),
    ("v31:biz-user-achievement:update", "编辑BizUserAchievement", "v31:biz-user-achievement:page"),
    ("v31:biz-user-achievement:delete", "删除BizUserAchievement", "v31:biz-user-achievement:page"),
    ("v31:biz-user-cosmetic:create", "新增BizUserCosmetic", "v31:biz-user-cosmetic:page"),
    ("v31:biz-user-cosmetic:update", "编辑BizUserCosmetic", "v31:biz-user-cosmetic:page"),
    ("v31:biz-user-cosmetic:delete", "删除BizUserCosmetic", "v31:biz-user-cosmetic:page"),
    ("v31:biz-user-equipment:create", "新增BizUserEquipment", "v31:biz-user-equipment:page"),
    ("v31:biz-user-equipment:update", "编辑BizUserEquipment", "v31:biz-user-equipment:page"),
    ("v31:biz-user-equipment:delete", "删除BizUserEquipment", "v31:biz-user-equipment:page"),
    (
        "v31:biz-user-growth-account:create",
        "新增BizUserGrowthAccount",
        "v31:biz-user-growth-account:page",
    ),
    (
        "v31:biz-user-growth-account:update",
        "编辑BizUserGrowthAccount",
        "v31:biz-user-growth-account:page",
    ),
    (
        "v31:biz-user-growth-account:delete",
        "删除BizUserGrowthAccount",
        "v31:biz-user-growth-account:page",
    ),
    (
        "v31:biz-user-growth-transaction:create",
        "新增BizUserGrowthTransaction",
        "v31:biz-user-growth-transaction:page",
    ),
    (
        "v31:biz-user-growth-transaction:update",
        "编辑BizUserGrowthTransaction",
        "v31:biz-user-growth-transaction:page",
    ),
    (
        "v31:biz-user-growth-transaction:delete",
        "删除BizUserGrowthTransaction",
        "v31:biz-user-growth-transaction:page",
    ),
    (
        "v31:biz-user-level-benefit:create",
        "新增BizUserLevelBenefit",
        "v31:biz-user-level-benefit:page",
    ),
    (
        "v31:biz-user-level-benefit:update",
        "编辑BizUserLevelBenefit",
        "v31:biz-user-level-benefit:page",
    ),
    (
        "v31:biz-user-level-benefit:delete",
        "删除BizUserLevelBenefit",
        "v31:biz-user-level-benefit:page",
    ),
    (
        "v31:biz-user-level-history:create",
        "新增BizUserLevelHistory",
        "v31:biz-user-level-history:page",
    ),
    (
        "v31:biz-user-level-history:update",
        "编辑BizUserLevelHistory",
        "v31:biz-user-level-history:page",
    ),
    (
        "v31:biz-user-level-history:delete",
        "删除BizUserLevelHistory",
        "v31:biz-user-level-history:page",
    ),
    (
        "v31:biz-user-point-account:create",
        "新增BizUserPointAccount",
        "v31:biz-user-point-account:page",
    ),
    (
        "v31:biz-user-point-account:update",
        "编辑BizUserPointAccount",
        "v31:biz-user-point-account:page",
    ),
    (
        "v31:biz-user-point-account:delete",
        "删除BizUserPointAccount",
        "v31:biz-user-point-account:page",
    ),
    (
        "v31:biz-user-point-transaction:create",
        "新增BizUserPointTransaction",
        "v31:biz-user-point-transaction:page",
    ),
    (
        "v31:biz-user-point-transaction:update",
        "编辑BizUserPointTransaction",
        "v31:biz-user-point-transaction:page",
    ),
    (
        "v31:biz-user-point-transaction:delete",
        "删除BizUserPointTransaction",
        "v31:biz-user-point-transaction:page",
    ),
    ("v31:biz-user-task:create", "新增BizUserTask", "v31:biz-user-task:page"),
    ("v31:biz-user-task:update", "编辑BizUserTask", "v31:biz-user-task:page"),
    ("v31:biz-user-task:delete", "删除BizUserTask", "v31:biz-user-task:page"),
    ("v31:tool:create", "新增Tool", "v31:tool:page"),
    ("v31:tool:update", "编辑Tool", "v31:tool:page"),
    ("v31:tool:delete", "删除Tool", "v31:tool:page"),
    ("v31:tool-access-policy:create", "新增ToolAccessPolicy", "v31:tool-access-policy:page"),
    ("v31:tool-access-policy:update", "编辑ToolAccessPolicy", "v31:tool-access-policy:page"),
    ("v31:tool-access-policy:delete", "删除ToolAccessPolicy", "v31:tool-access-policy:page"),
    ("v31:tool-category:create", "新增ToolCategory", "v31:tool-category:page"),
    ("v31:tool-category:update", "编辑ToolCategory", "v31:tool-category:page"),
    ("v31:tool-category:delete", "删除ToolCategory", "v31:tool-category:page"),
    (
        "v31:tool-component-registry:create",
        "新增ToolComponentRegistry",
        "v31:tool-component-registry:page",
    ),
    (
        "v31:tool-component-registry:update",
        "编辑ToolComponentRegistry",
        "v31:tool-component-registry:page",
    ),
    (
        "v31:tool-component-registry:delete",
        "删除ToolComponentRegistry",
        "v31:tool-component-registry:page",
    ),
    (
        "v31:tool-popularity-daily:create",
        "新增ToolPopularityDaily",
        "v31:tool-popularity-daily:page",
    ),
    (
        "v31:tool-popularity-daily:update",
        "编辑ToolPopularityDaily",
        "v31:tool-popularity-daily:page",
    ),
    (
        "v31:tool-popularity-daily:delete",
        "删除ToolPopularityDaily",
        "v31:tool-popularity-daily:page",
    ),
    ("v31:tool-recent-usage:create", "新增ToolRecentUsage", "v31:tool-recent-usage:page"),
    ("v31:tool-recent-usage:update", "编辑ToolRecentUsage", "v31:tool-recent-usage:page"),
    ("v31:tool-recent-usage:delete", "删除ToolRecentUsage", "v31:tool-recent-usage:page"),
    ("v31:tool-usage-daily:create", "新增ToolUsageDaily", "v31:tool-usage-daily:page"),
    ("v31:tool-usage-daily:update", "编辑ToolUsageDaily", "v31:tool-usage-daily:page"),
    ("v31:tool-usage-daily:delete", "删除ToolUsageDaily", "v31:tool-usage-daily:page"),
    ("v31:tool-usage-event:create", "新增ToolUsageEvent", "v31:tool-usage-event:page"),
    ("v31:tool-usage-event:update", "编辑ToolUsageEvent", "v31:tool-usage-event:page"),
    ("v31:tool-usage-event:delete", "删除ToolUsageEvent", "v31:tool-usage-event:page"),
    ("v31:tool-version:create", "新增ToolVersion", "v31:tool-version:page"),
    ("v31:tool-version:update", "编辑ToolVersion", "v31:tool-version:page"),
    ("v31:tool-version:delete", "删除ToolVersion", "v31:tool-version:page"),
    ("v31:blog-article:create", "新增BlogArticle", "v31:blog-article:page"),
    ("v31:blog-article:update", "编辑BlogArticle", "v31:blog-article:page"),
    ("v31:blog-article:delete", "删除BlogArticle", "v31:blog-article:page"),
    ("v31:blog-article-tag:create", "新增BlogArticleTag", "v31:blog-article-tag:page"),
    ("v31:blog-article-tag:update", "编辑BlogArticleTag", "v31:blog-article-tag:page"),
    ("v31:blog-article-tag:delete", "删除BlogArticleTag", "v31:blog-article-tag:page"),
    ("v31:blog-article-version:create", "新增BlogArticleVersion", "v31:blog-article-version:page"),
    ("v31:blog-article-version:update", "编辑BlogArticleVersion", "v31:blog-article-version:page"),
    ("v31:blog-article-version:delete", "删除BlogArticleVersion", "v31:blog-article-version:page"),
    ("v31:blog-author:create", "新增BlogAuthor", "v31:blog-author:page"),
    ("v31:blog-author:update", "编辑BlogAuthor", "v31:blog-author:page"),
    ("v31:blog-author:delete", "删除BlogAuthor", "v31:blog-author:page"),
    (
        "v31:blog-author-application:create",
        "新增BlogAuthorApplication",
        "v31:blog-author-application:page",
    ),
    (
        "v31:blog-author-application:update",
        "编辑BlogAuthorApplication",
        "v31:blog-author-application:page",
    ),
    (
        "v31:blog-author-application:delete",
        "删除BlogAuthorApplication",
        "v31:blog-author-application:page",
    ),
    ("v31:blog-category:create", "新增BlogCategory", "v31:blog-category:page"),
    ("v31:blog-category:update", "编辑BlogCategory", "v31:blog-category:page"),
    ("v31:blog-category:delete", "删除BlogCategory", "v31:blog-category:page"),
    ("v31:blog-comment:create", "新增BlogComment", "v31:blog-comment:page"),
    ("v31:blog-comment:update", "编辑BlogComment", "v31:blog-comment:page"),
    ("v31:blog-comment:delete", "删除BlogComment", "v31:blog-comment:page"),
    ("v31:blog-favorite:create", "新增BlogFavorite", "v31:blog-favorite:page"),
    ("v31:blog-favorite:update", "编辑BlogFavorite", "v31:blog-favorite:page"),
    ("v31:blog-favorite:delete", "删除BlogFavorite", "v31:blog-favorite:page"),
    ("v31:blog-like:create", "新增BlogLike", "v31:blog-like:page"),
    ("v31:blog-like:update", "编辑BlogLike", "v31:blog-like:page"),
    ("v31:blog-like:delete", "删除BlogLike", "v31:blog-like:page"),
    ("v31:blog-tag:create", "新增BlogTag", "v31:blog-tag:page"),
    ("v31:blog-tag:update", "编辑BlogTag", "v31:blog-tag:page"),
    ("v31:blog-tag:delete", "删除BlogTag", "v31:blog-tag:page"),
    ("v31:blog-user-follow:create", "新增BlogUserFollow", "v31:blog-user-follow:page"),
    ("v31:blog-user-follow:update", "编辑BlogUserFollow", "v31:blog-user-follow:page"),
    ("v31:blog-user-follow:delete", "删除BlogUserFollow", "v31:blog-user-follow:page"),
]

__all__ = ["V31_BUTTONS", "V31_MENUS", "V31_MENU_PAGES", "V31_PAGES"]
